diffblue/cbmc

.travis.yml
README.md

Given the recent initial commit of README.md some manual merge will be necessary, but anyway my README.md would link to the wrong Travis instance.
Best,
Michael

Integration with Travis CI, extended README.md

---

src/goto-programs/builtin_functions.cpp

According to http://sv-comp.sosy-lab.org/2016/rules.php, SV-COMP is moving towards __VERIFIER_atomic_{begin,end} that work exactly like __CPROVER_atomic_{begin,end} instead of using prefixes to function names.
Best,
Michael

Support SV-COMP's __VERIFIER_atomic_{begin,end}

---

regression/cbmc/guard1/main.c
regression/cbmc/guard1/test.desc
src/util/guard.cpp

Since r6259 guardt::is_false() is just exprt's is_false() instead of
a full loop testing each conjunct.

Force the guard to false_exprt() whenever false is added to the conjunction

---

src/goto-cc/compile.cpp
src/linking/linking.cpp
src/util/message_stream.h

This series of patches improves the diagnostic output in case of linking problems for enum types, and also fixes the problem of inconsistent type renaming when linking 3 or more files.
This is a duplicate of #7 after restoring all links to the SVN.

Enum linking

---

src/util/merge_irep.cpp

We otherwise lose, e.g., ID_C_SSA_symbol

merge_irept should not destroy comments (but it may ignore differences)

---

src/goto-instrument/full_slicer.cpp
src/goto-instrument/full_slicer.h
src/goto-instrument/full_slicer_class.h
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h

This is a duplicate of #10 after restoring all links to the SVN.

Slice with respect to select properties

---

src/goto-analyzer/taint_analysis.cpp
src/goto-programs/goto_convert_functions.cpp
src/jsil/Makefile
src/jsil/jsil_convert.cpp
src/jsil/jsil_internal_additions.cpp
src/jsil/jsil_language.cpp
src/jsil/jsil_language.h
src/jsil/jsil_parse_tree.cpp
src/jsil/jsil_parse_tree.h
src/jsil/jsil_typecheck.cpp
src/jsil/jsil_typecheck.h
src/jsil/jsil_types.cpp
src/jsil/jsil_types.h
src/jsil/parser.y

This enables conversion from Javascript to goto programs

Started type checking jsil programs

---

src/linking/linking.cpp

Further extensions to the goto-binary linker to deal with more cases showing up in practice.

Linking of functions with/without ellipsis or transparent-union/POD conflicts

---

src/ansi-c/ansi_c_language.cpp
src/ansi-c/cprover_library.cpp
src/ansi-c/parser.y

This is a duplicate of #5 after restoring all links to the SVN.

Minor cleanup of the ansi-c parser: consistent use of init

---

src/ansi-c/c_storage_spec.cpp
src/ansi-c/c_typecheck_base.cpp
src/goto-programs/read_goto_binary.cpp
src/linking/linking.cpp

Linking and type checking for weak symbols

---

src/goto-symex/symex_function_call.cpp

Also improves the readability of error output when argument conversion is denied

Transparent unions require argument conversion, do this for all union types

---

src/java_bytecode/java_bytecode_convert.cpp

Fixes if_expr1 regresion test.

Fix java bytecode translation of control-flow joins

---

src/ansi-c/ansi_c_convert_type.cpp

Follow-up to 3f01cce50a to support
`void foo() __attribute__((constructor));` in addition to
`void __attribute__((constructor)) foo();`

Support for postfixed __attribute__((constructor))

---

regression/cbmc/Local_out_of_scope2/main.c
regression/cbmc/Local_out_of_scope2/test.desc
src/goto-symex/symex_function_call.cpp

a5bc493713 introduced cases where information in the frame may become
inconsistent with the actual renaming being used, as shown in the regression
test.

Fix consistency error in SSA level 1 renaming

---

src/ansi-c/c_typecheck_argc_argv.cpp
src/ansi-c/c_typecheck_base.cpp
src/ansi-c/c_typecheck_code.cpp
src/ansi-c/c_typecheck_expr.cpp
src/ansi-c/c_typecheck_initializer.cpp
src/ansi-c/c_typecheck_type.cpp

Also cleanup: remove error_msg() calls that are only sometimes present;
exception handler will take care of outputting the error message.

Output source location with all type checking errors

---

regression/ansi-c/asm3/test.desc
regression/cbmc/gcc_attribute_alias1/main.c
regression/cbmc/gcc_attribute_alias1/test.desc
src/ansi-c/ansi_c_convert_type.cpp
src/ansi-c/c_storage_spec.cpp
src/ansi-c/c_storage_spec.h
src/ansi-c/c_typecheck_base.cpp
src/ansi-c/c_typecheck_base.h
src/ansi-c/c_typecheck_expr.cpp
src/ansi-c/library/unistd.c
src/ansi-c/parser.y
src/ansi-c/scanner.l
src/goto-cc/compile.cpp
src/goto-programs/goto_convert_functions.cpp
src/goto-programs/read_goto_binary.cpp
src/linking/linking.cpp
src/linking/static_lifetime_init.cpp

Full support for GCC asm labels and the alias attribute, as used by C libraries and other low-level code.

Gcc asm labels and attribute "alias" support

---

src/cbmc/cbmc_dimacs.cpp

Cleanup: Name should precede literals in output

Include _Bool variables in dimacs output, cleanup

---

regression/ansi-c/gcc_attributes5/main.c
regression/ansi-c/gcc_attributes5/test.desc
regression/ansi-c/gcc_attributes6/test.desc
regression/ansi-c/gcc_attributes9/main.c
regression/ansi-c/gcc_attributes9/test.desc
src/ansi-c/ansi_c_convert_type.cpp
src/ansi-c/c_storage_spec.cpp
src/ansi-c/c_storage_spec.h
src/ansi-c/c_typecheck_base.cpp
src/ansi-c/c_typecheck_type.cpp
src/ansi-c/parser.y
src/ansi-c/parser_static.inc
src/ansi-c/scanner.l
src/util/irep_ids.txt

Includes support for __attribute__((section("foo"))) and fixes existing regression tests that were marked KNOWNBUG. Built on top of #50, hence half of the patch series is redundant.

Extended GCC attributes parsing and processing

---

src/analyses/invariant_set.h
src/big-int/bigint-test.cc
src/big-int/bigint.cc
src/json/json_parser.cpp
src/util/lispexpr.h
src/util/pipe_stream.cpp
src/util/string_container.cpp
src/xmllang/parser.y
src/xmllang/scanner.l
src/xmllang/xml_parser.cpp

Use C++ headers instead of C-style ones wherever possible. (Some of them could likely be removed entirely.)

Proper C++ includes

---

regression/cbmc-concurrency/norace_array1/main.c
regression/cbmc-concurrency/norace_array1/test.desc
regression/cbmc-concurrency/norace_scalar1/main.c
regression/cbmc-concurrency/norace_scalar1/test.desc
regression/cbmc-concurrency/norace_struct1/main.c
regression/cbmc-concurrency/norace_struct1/test.desc

For #123 
These are simpler than 
regression/cbmc-concurrency/struct_and_array1 
that exhibits the same problem (currently deactivated as KNOWNBUG)...

Concurrency regression tests for arrays and structs

---

src/cbmc/bmc.cpp

If there's a design decision that SAFE/exit 0 should only ever be returned when safety is proven, and --outfile thus correctly has a non-zero exit code, then the regression test Malloc22 must be fixed instead.

Successfully producing a formula with --outfile should not yield non-zero exit

---

regression/ansi-c/struct6/test.desc
regression/cpp/Address_of_Method2/test.desc
regression/cpp/Address_of_Method3/test.desc
regression/cpp/Constant2/test.desc
regression/cpp/Constant3/test.desc
regression/cpp/Pointer_Conversion1/test.desc
regression/cpp/Resolver12/test.desc
regression/cpp/Resolver4/test.desc
regression/cpp/union3/test.desc
regression/cpp/union4/test.desc
regression/cpp/union5/test.desc
src/goto-cc/armcc_mode.cpp
src/goto-cc/armcc_mode.h
src/goto-cc/cw_mode.cpp
src/goto-cc/cw_mode.h
src/goto-cc/gcc_mode.cpp
src/goto-cc/gcc_mode.h
src/goto-cc/goto_cc_mode.cpp
src/goto-cc/goto_cc_mode.h
src/goto-cc/ld_mode.cpp
src/goto-cc/ld_mode.h
src/goto-cc/ms_cl_mode.cpp
src/goto-cc/ms_cl_mode.h

This change enables proper cleanup via destructors instead of premature calls to
exit().
ARM/CW/CL modes continue to exit with EX_USAGE in case of errors, which might
not actually match the behaviour of armcc/Codewarrior/cl.

GCC mode of goto-cc uses GCC's exit code, proper cleanup of files

---

regression/ansi-c/pragma_pack3/main.c
src/ansi-c/ansi_c_convert_type.cpp
src/ansi-c/padding.cpp
src/ansi-c/parser.y

Quoting the documentation: "The alignment of a member will be on a
boundary that is either a multiple of n or a multiple of the size of the
member, whichever is smaller."

pragma pack(n) still permits more dense alignment than n

---

src/linking/linking.cpp
src/linking/linking_class.h

Several further relaxations that can be handled without affecting soundness.

Relaxed linking

---

regression/cbmc/null3/main.c
regression/cbmc/null3/test.desc
src/goto-symex/symex_builtin_functions.cpp
src/util/simplify_expr.cpp
src/util/simplify_expr_array.cpp
src/util/simplify_expr_class.h
src/util/simplify_expr_int.cpp
src/util/simplify_expr_pointer.cpp

A first set of cleanup and extensions to the simplifier. There is more to come, which will build on those changes, notably 794deb7.
This is a duplicate of #12 after restoring all links to the SVN.

Simplifier 20160305

---

src/solvers/flattening/bv_pointers.cpp

Expressions used in the context of unbounded arrays may still be subject to object_size or other pointer-related operations. Thus they need to be seen before evaluating object_size.

Evaluating object_size requires pointer_logic.objects fully populated

---

src/goto-instrument/goto_instrument_parse_options.cpp

GCC asm labels need to be considered when listing undefined functions

---

regression/cbmc/enum5/main.c
regression/cbmc/enum5/test.desc
src/util/base_type.cpp

The implementation relies on type internals, using get(ID_identifier)
instead of get_identifier() to keep the patch small.

Support for tag types in base_type_eq

---

src/java_bytecode/java_bytecode_typecheck_code.cpp

Upcasts might happen in the immediate argument to a switch statement (e.g. switch(((A*)x)->y) needing to become switch(x->superclass.y)). The Java bytecode typechecker already looked at some contexts for possible implicit casts like this; this adds switch arguments to the list. Fixes #154.

Fix switch values that need an implicit upcast to find a struct member

---

src/Makefile
src/analyses/dependence_graph.h
src/goto-diff/Makefile
src/goto-diff/change_impact.cpp
src/goto-diff/change_impact.h
src/goto-diff/goto_diff.h
src/goto-diff/goto_diff_base.cpp
src/goto-diff/goto_diff_languages.cpp
src/goto-diff/goto_diff_main.cpp
src/goto-diff/goto_diff_parse_options.cpp
src/goto-diff/goto_diff_parse_options.h
src/goto-diff/scripts/diff-filter.pl
src/goto-diff/syntactic_diff.cpp
src/goto-diff/syntactic_diff.h
src/goto-diff/unified_diff.cpp
src/goto-diff/unified_diff.h

basic syntactic diffing
requires pull request #62

Basic version of goto-diff tool

---

src/cbmc/all_properties.cpp
src/cbmc/bmc.cpp
src/cbmc/bmc_cover.cpp
src/goto-programs/json_goto_trace.cpp
src/goto-programs/loop_ids.cpp
src/goto-programs/show_properties.cpp
src/util/Makefile
src/util/json_expr.cpp
src/util/json_expr.h

JSON output with error trace, property id and status for all properties and stop-on-fail

More JSON output

---

src/goto-instrument/goto_program2code.cpp

When the instruction causing dead code is skipped, the dead instructions must
not be generated either as demonstrated by #170.
Fixes #170.

dump-c: do not output dead instructions

---

src/java_bytecode/java_bytecode_convert_method.cpp

Thread synchronization is currently not supported in Java. Emit warning
upon entering a critical section which is marked by `monitorenter`,
simply skip `monitorexit`.
temporary fix for #153

skip monitorenter / monitorexit

---

src/ansi-c/ansi_c_entry_point.cpp
src/ansi-c/expr2c.cpp
src/ansi-c/expr2c_class.h
src/cbmc/cbmc_parse_options.cpp
src/java_bytecode/java_entry_point.cpp

Test inputs and outputs for C and Java

---

src/java_bytecode/bytecode_info.h
src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_parse_tree.h
src/java_bytecode/java_bytecode_parser.cpp

This corrects local variable usage which depends on local frames. If present, the LocalVarTable contains information about the local variable scope. This scope is defined for a variable with index `n` via `start_pc` and `length`.
Instead of `variablet`, the `expanding_vector` `variables` now contains a `std::vector<variablet>` for each index. For an instruction at address `a`, the corresponding variable is searched as the valid variable for the frame `start_pc <= a + length(instruction) < start_pc + length`.
resolve #177

Fix local var frame

---

src/java_bytecode/java_bytecode_parser.cpp

This supports loading class refs that only appear in the local variable
table. Not doing so result in some cases in an error of type `failed to
find type symbol`.
resolve #187

add classes of local var table to class_ref

---

doc/html-manual/cover.shtml
doc/html-manual/pid.c

Updated the CPROVER manual, by adding a case study on test case generation following code coverage. In particular, the ``--cover mcdc`` option of  CBMC is investigated.

Added a case study into the CPROVER manual on test case generation

---

.gitignore
src/java_bytecode/java_bytecode_convert_method.cpp

minisat, zlib and glucose are automatically downloaded into the repository tree, but are not to be committed. Therefore they should be in .gitignore.
Also constructor was missing the 's' in one function name.

Improve gitignore and fix a typo

---

doc/html-manual/cover.shtml
doc/html-manual/pid.c

- specify input parameters for the PID function more clearly
- non-deterministically assign input values at each loop iteration

Clarified the inputs for the PID case study.

---

src/cbmc/bmc.h
src/cbmc/show_vcc.cpp

Output vccs in json format

---

src/pointer-analysis/value_set_dereference.cpp
src/util/pointer_offset_size.cpp
src/util/pointer_offset_size.h

Symex: synthesise clean references to subfields and/or array indices when addressing subexpressions

---

src/goto-programs/read_bin_goto_object.cpp

Location numbers are not stored in v3 goto binaries. Reading from
binaries up to now only invoked update() on a per-function level. The
additional goto_functionst::compute_location_numbers() ensures globally
unique location numbers. Fixes #313.

Ensure globally unique location numbers after reading binary

---

src/pointer-analysis/value_set.cpp
src/pointer-analysis/value_set_fivr.cpp
src/pointer-analysis/value_set_fivrns.cpp

https://github.com/diffblue/cbmc/issues/281
was fixed by:
https://github.com/diffblue/cbmc/pull/288
this copies the fix to other pointer analysis domains.  Without this, some of the functionality of goto-instrument is broken.

Repeat the from pull request #288 for other domains.

---

regression/ansi-c/function_return1/main.c
regression/ansi-c/function_return1/test.desc
src/ansi-c/c_typecheck_code.cpp

Also included a simple regression that should produce this warning

Added a warning for when function returns a value but has return void

---

src/Makefile

https://github.com/diffblue/cbmc/commit/6b21f364f215a4bf9b5884b727943486d50f7827 changed the name of the archive that is downloaded, but did not adapt subsequent steps. This PR fixes that.

Fix libzip-download make rule

---

regression/cbmc-with-incr/Struct_Bytewise1/struct_bytewise.c
regression/cbmc/Struct_Bytewise1/struct_bytewise.c

Hi!
This patch fixes two typos which I stumbled over being one of Debian's m68k porters.
The code checks for m68k by looking whether `__mk68k__` is defined. However, the proper definition to look for is `__m68k__`:
`(sid-m68k-sbuild)root@ikarus:/# echo | gcc -E -dM - |grep mk68`
`(sid-m68k-sbuild)root@ikarus:/# echo | gcc -E -dM - |grep m68k`
`#define __m68k__ 1`
`(sid-m68k-sbuild)root@ikarus:/#`
This was tested with gcc-6.2.1 on Debian/m68k.
Thanks,
Adrian

Fix typos in struct_bytewise (__mk68k__ -> __m68k__)

---

src/java_bytecode/java_bytecode_convert_method.cpp

dup2, pop2 et al operate on *words*, and thus duplicate two 32-bit entities or one 64-bit entity. However simply comparing the CBMC type-width isn't sufficient, as we use 64-bit pointers for our own convenience while the JVM uses a 32-bit pointer. This patch introduces a simple helper function that gives the argument's JVM type width instead of its actual width.
The bug can be reproduced by unpacking http://central.maven.org/maven2/org/springframework/spring-core/3.2.14.RELEASE/spring-core-3.2.14.RELEASE.jar and running `goto-analyzer org/springframework/asm/ClassReader.class`, whose method `readConst` (amongst others) uses `dup2_x1` and `pop2` in concert to reorder integer and pointer arguments on the stack. Without the fix the resulting goto program tries to cast an int32 illegally into …

Fix dup2, pop2 et al operating on pointers

---

src/goto-symex/goto_symex_state.cpp

Array type mismatch bugfix

---

src/ansi-c/c_preprocess.cpp

According to cpp -dM < /dev/null this is defined by default by GCC. It
seems it now also is required on cygwin, according to a discussion on
the mailing list.

Define __INT32_TYPE__ as required on cygwin

---

.travis.yml

This is an attempt to cleanup the travis configuration. It includes 1994969 from #342.

Travis reconfig

---

regression/cbmc/Float-to-int1/main.c
regression/cbmc/Float-to-int1/test.desc
regression/cbmc/Float-to-int2/main.c
regression/cbmc/Float-to-int2/test.desc
regression/cbmc/Float-to-int3/main.c
regression/cbmc/Float-to-int3/test.desc
src/solvers/floatbv/float_utils.cpp

This affects cases when a floating-point number is cast to an integer
which is longer than the significand of the float and the exponent is
greater than the length of the significand.  This includes
float -> (u)int32_t and double -> (u)int64_t.  These were incorrectly
converted to 0.

Fix a bug in the bitwise encoding of float to int casting.

---

regression/test.pl

If the fourth line starts with a `-` we pass that line as flags to the grep command when checking the lines in this test. This allows for tests to pass flags such as: `-Pzo` to [check multiple consecutive lines](http://stackoverflow.com/questions/3717772/regex-grep-for-multi-line-search-needed/7167115#7167115).
I needed multi-line checking as I want to verify that, when outputting a symbol table, a specific variable has a specific type and a different variable has a different type. Therefore checking the existence of these lines is not sufficient to verify the outcome. 
I have run all the old tests in CBMC to check there aren't any that will inadvertently activate this feature. I will try across all directories to check, however, there may be a cleaner way that will preserve backwards …

Allowed test.desc to pass flags to the grep command

---

.travis.yml
src/solvers/miniBDD/miniBDD.cpp

The build matrix is constructed from os and compiler.
This should re-enable linting as a parallel, separate task.

Reconfigure travis to perform parallel builds and linting

---

src/ansi-c/library/stdio.c

fflush(NULL) flushes all open streams if the argument is NULL.
Thus `stream` must not be dereferenced unconditionally.

C library: fflush(NULL) is permitted

---

src/cbmc/bmc.cpp
src/goto-programs/graphml_witness.cpp
src/goto-programs/graphml_witness.h
src/xmllang/graphml.cpp
src/xmllang/graphml.h

This covers the first 7 commits of https://github.com/diffblue/cbmc/pull/363

Graphml correctness witnesses

---

regression/goto-instrument/const-struct1/main.c
regression/goto-instrument/const-struct1/test.desc

Const structs are not storing their const-ness inside the symbol table. This regression test exhibits this behaviour. Marked as KNOWNBUG (is issue #355)

Added a regression to demonstrate const structs

---

.travis.yml
src/goto-instrument/unwind.cpp
src/goto-instrument/unwind.h
src/goto-programs/goto_program_template.h

Hacking a const iterator into a non-const one should be available at global scope instead of unwind-local.

Replace get_mutable by goto_programt API function

---

src/Makefile

1.2.8 is no longer on their website, so `make zlib-download` was failing.

Update zlib to latest - 1.2.10

---

src/ansi-c/ansi_c_entry_point.cpp
src/ansi-c/ansi_c_language.cpp
src/cbmc/cbmc_parse_options.cpp
src/java_bytecode/java_entry_point.cpp

Corrected lint errors in some files as they were touched by #338.
There are some outstanding errors that I wasn't sure how to fix:
- an anonomous namespace in java_entry_point.cpp
- The formatting of the CBMC help message
There are also some bugs with the linter incorrectly reporting errors.

Fixing lint errors in files touched by PR #338

---

src/java_bytecode/java_bytecode_convert_method.cpp

Anonymous variables' names could previously clash with user-defined ones. This puts anonymous variables in a different namespace and gives them names guaranteed to be unique from each other based on their declaration program point.
Part of the Java local variable table PR series; see the companion PR against testgen for more detail: https://github.com/diffblue/cbmc-testgen/pull/28

Prevent anonymous and named variables from clashing

---

src/java_bytecode/java_bytecode_convert_class.cpp

Trivial fix. See https://github.com/diffblue/cbmc/issues/383 for details.

Don't call `java_array_type('\0')`. Fixes #383

---

src/java_bytecode/java_bytecode_convert_method.cpp

This commit leaves them with a nil value, to differentiate them from a method that actually has an empty body (i.e. `{}`) It has no immediate impact, but will make forthcoming changes easier as we can assume that every non-nil method has at least one instruction.
Abstract methods are treated similarly (this mirrors a change already in place in the `test_gen` branch, which again seeks to differentiate an empty body from an undefined method)

Don't convert native methods

---

src/java_bytecode/java_bytecode_convert_method.cpp

The existing code tried to infer local type from the assignment, but (a) the information wasn't recorded in the variable table leading to later misuse, and (b) I'm not convinced it's safe to infer types for locals this way because a pattern like if(x) a = new A(); else a = new B(); (where A and B are unrelated) can use the same local slot for both classes. In this case we'd want to give it java.lang.Object* type.
In view of all this it is surely simplest to just treat locals as generic, like the bytecode does, then cast the void* to needed types at use sites.
Companion of https://github.com/diffblue/cbmc-testgen/pull/34 -- part of the local variable table improvement series.

Treat all anonymous locals as void*

---

src/java_bytecode/java_bytecode_convert_method.cpp

See https://github.com/diffblue/cbmc-testgen/pull/32 for the original description of this PR. Recommend reviewing by commit, as the first makes the functional change (adding symbol table entries for locals) and the second does general style cleanup that Peter requested.

Add Java local variable symbols

---

src/cegis/cegis-util/program_helper.cpp

Goto_programt received an additional insert_before in a recent commit. This
made this reference to it ambiguous. Fixed using a static_cast.

Fixed ambiguity in mem_fun.

---

regression/goto-instrument/data-flow1/main.c
regression/goto-instrument/data-flow1/test.desc
src/analyses/ai.cpp
src/analyses/custom_bitvector_analysis.cpp
src/analyses/custom_bitvector_analysis.h
src/analyses/dependence_graph.cpp
src/analyses/dependence_graph.h
src/analyses/escape_analysis.cpp
src/analyses/escape_analysis.h
src/analyses/global_may_alias.cpp
src/analyses/global_may_alias.h
src/analyses/invariant_set_domain.h
src/analyses/is_threaded.cpp
src/analyses/reaching_definitions.cpp
src/analyses/reaching_definitions.h
src/analyses/uninitialized_domain.cpp
src/analyses/uninitialized_domain.h

Even when the merge of state into the initial location of a function has
no effect, the function must be analyzed. Otherwise effects on global
variables may not be seen.
This had already been fixed in static_analyist in 2e2df0dd1.
Fixes #325

Data-flow analysis must always enter new function

---

regression/goto-instrument/data-flow1/test.desc

This checked for a hardcoded location number, but that varied from build to build due to nondeterministic ordering of functions in the GOTO binary file. Instead just check for the right number of dependencies.

Fix data-flow1 test

---

src/util/string_utils.cpp

Result of split_string() can be empty

---

regression/cbmc/unsigned___int128/main.c
regression/cbmc/unsigned___int128/test.desc
src/ansi-c/c_types.cpp

Includes regression test provided by Vladimir Klebanov.

Fix typo in definition of unsigned __int128

---

regression/goto-instrument/chain.sh
regression/goto-instrument/restore-returns1/test.desc
regression/goto-instrument/restore-returns2/test.desc
regression/goto-instrument/slice-global-inits1/main.c
regression/goto-instrument/slice-global-inits1/test.desc
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-programs/Makefile
src/goto-programs/slice_global_inits.cpp
src/goto-programs/slice_global_inits.h

Adds an option ``--slice-global-inits`` to remove initializations of global variables from ``__CPROVER_initialize()`` that are not used by functions reachable from the entry point. This is useful in conjunction with ``--function`` when there are lots of globals and the given function and its callees only access a small subset of them.

Remove initializations of unused global variables

---

regression/cpp-linter/function-comment-header6/main.cpp
scripts/cpplint.py

Issue: https://github.com/diffblue/cbmc-testgen/issues/62 [private]
The regex for finding operator functions didn't work if the function belonged to a class as it wasn't matching the :: correctly. Extended the regression test to cover this.

Corrected regex for member operator functions

---

scripts/cpplint.py

There is an exception to the function body rule that was being incorrectly applied in, for example [line 236 for java_bytecode_convert_method.cpp](https://github.com/diffblue/cbmc/blob/master/src/java_bytecode/java_bytecode_convert_method.cpp#L236). The problem was incorrect indentation causing the code to be run even when the function shoudn't have been checked.

Fixed a bug in all caps functions without function bodies

---

.travis.yml
scripts/run_lint.sh

Issue: https://github.com/diffblue/cbmc-testgen/issues/59 [private]
Added a Bash script that uses log to work out what commits have been modified. It then filters blame based on these commits to work out what lines have been touched since master. Finally it uses grep to filter the output of the linting script based only on lines that have been modified.
This is then called from Travis so PRs can show just relevant errors. This isn't to say that the other errors shouldn't be fixed, but hopefully rather than ignoring all the linting errors will be able to provide more precise information. 
A demo of it should hopefully be seen here: https://github.com/diffblue/cbmc/pull/406

Modify Travis to only run the linter on modified lines

---

scripts/run_lint.sh

Previously, as we had set -e enabled, the final grep (filtering relevant errors) would fail if there were no errors to find. This failure was causing the script to exit with an error code (causing the CI to think
the lint had failed). Now we ignore whether the grep fails or not.
Also added a error for if the script is missing.

Fix for lint failing when no linting errors

---

CODING_STANDARD
regression/cpp-linter/throw/main.cpp
regression/cpp-linter/throw/test.desc
scripts/cpplint.py

Throw statements should not have the bracket and the first character of the error message should be lower case. Added a check to the linter to verify this. Added regression tests to check this.
Also updated the coding standard to make these rules explicit.

Adding check for throw formatting

---

CODING_STANDARD
regression/cpp-linter/multi-line-function-call1/main.cpp
regression/cpp-linter/multi-line-function-call1/test.desc
regression/cpp-linter/multi-line-function-call2/main.cpp
regression/cpp-linter/multi-line-function-call2/test.desc
regression/cpp-linter/multi-line-function-call3/main.cpp
regression/cpp-linter/multi-line-function-call3/test.desc
scripts/cpplint.py

Previously the lint check for function calls that had there args split over several lines was quite restricted in what it could detect. This extends the check to correctly deal with function calls that contain function calls inside them (nested). It also ignores `if`/`for`/`catch`/`while`/`switch` statements that have different formatting rules.
Added regression tests to check all the different cases of formatting where this rule should and shouldn't apply.

Lint checks nested function calls broken over multiple lines

---

scripts/run_lint.sh

Add colon to end of pattern to prevent recognising lines that start with the number of a valid line

Prevent recognising lines by prefix

---

scripts/run_lint.sh

This allows use of the lint script without changing to the root of the CBMC folder first; e.g. to lint a non-CBMC project

Allow lint to be called from any folder

---

scripts/run_lint.sh

Previously we would try and run git blame on a deleted file (since would still show up in the diff) which would cause an error. Now we just skip over such files.

Run lint script handling deleted files

---

COMPILING
regression/get_coverage.sh

getCoverage.sh is a script that will provide an HTML report of the code coverage that the regression tests give. The details of how to run and the high level details of the script are in COMPILING.

Code coverage for regression tests.

---

src/ansi-c/expr2c.cpp
src/ansi-c/expr2c_class.h

In preparation for a class which provides a more accurate C generation, moved a bunch of the conversion functions into there own functions that can be overriden.

Extracted functions from the convert/convert_type methods in expr2c

---

regression/Makefile
regression/goto-analyzer/intervals2/test.desc
regression/goto-analyzer/intervals4/test.desc

The two tests that fail appear to be real bugs as the conditions appear to be sufficient to conclude the assertion. I also added this folder to the regressions that get run since excluding these two the remainder
pass.
I shall create an issue for this, but if someone with more knowledge could confirm that my assessment that a) this should work and b) my suggested issue is correct that would be useful. 
I have also added this folder to the regressions that get run by the CI. 
**Proposed Issue**
The intervals analysis of goto-analyze doesn't work for intervals2 and intervals4. Both of these use && in an assertion that should be knowable.

Mark the two failing bugs in regressions/goto-analyzer as KNOWNBUG

---

.gitignore

If you run the coverage script introduced in #391 it generates a folder containing the results. This adds these generated files to the git ignore. 
The only reason why this might be a bad thing to ignore is if at some point we want a CI to run this script and make the results viewable somewhere. However, in this case I suspect it needs to not be in a randomly generated folder name but instead somewhere specific.

Ignore any files generated by the regression script

---

src/Makefile

Previous version 1.2.10 is not accessible any more.

ZLib has been bumped to version 1.2.11.

---

src/java_bytecode/java_bytecode_convert_method.cpp

Java 8 lambdas are implemented using the `invokedynamic` instruction. Handling them correctly requires runtime code generation, or static analysis to achieve the same result; in the meantime this patch at least returns something of the right type, so subsequent conversion stages don't choke on an unexpected `nil_exprt`.

Stub Java 8 lambdas

---

src/solvers/qbf/qbf_bdd_core.cpp
src/solvers/qbf/qbf_bdd_core.h
src/solvers/qbf/qbf_quantor.cpp
src/solvers/qbf/qbf_qube.cpp
src/solvers/qbf/qbf_qube_core.cpp
src/solvers/qbf/qbf_qube_core.h
src/solvers/qbf/qbf_skizzo.cpp
src/solvers/qbf/qbf_skizzo_core.cpp
src/solvers/qbf/qbf_skizzo_core.h
src/solvers/qbf/qbf_squolem.cpp
src/solvers/qbf/qbf_squolem_core.cpp
src/solvers/qbf/qbf_squolem_core.h
src/solvers/qbf/qdimacs_core.cpp

Mostly white space issues, added some range based for loops. Went through to check the linting script is not producing any false positives. This folder now has 0 linting warnings.

Addressing linting errors in solvers/qbf

---

regression/test.pl

Some test cases auto-generated by Matthias' code included spaces, dollar-signs and such. This quotes them properly in test.pl.

Allow test script to operate on directories containing special chars

---

src/.dir-locals.el

This sets Linux-style C indenting (cf. GNU-style default; AFAIK editorconfig cannot say this)
and sets indent to 2-spaces no-tabs in case you don't have the editorconfig plugin installed

Add emacs config

---

regression/goto-instrument/dependence-graph1/main.c
regression/goto-instrument/dependence-graph1/test.desc
src/analyses/ai.cpp
src/analyses/dependence_graph.h

@lucasccordeiro Please check if that works for you.
Related to #260.

Dependency graph fix

---

regression/cbmc/byte_update1/main.c
regression/cbmc/byte_update1/test.desc
regression/cbmc/byte_update2/main.c
regression/cbmc/byte_update2/test.desc
regression/cbmc/byte_update3/main.c
regression/cbmc/byte_update3/test.desc
regression/cbmc/byte_update4/main.c
regression/cbmc/byte_update4/test.desc
regression/cbmc/byte_update5/main.c
regression/cbmc/byte_update5/test.desc
regression/cbmc/byte_update6/main.c
regression/cbmc/byte_update6/test.desc
regression/cbmc/byte_update7/main.c
regression/cbmc/byte_update7/test.desc
src/solvers/flattening/flatten_byte_operators.cpp
src/solvers/flattening/flatten_byte_operators.h

This fixes byte update flattening when applied to arrays with elements larger than a byte, which was previously unsound. It also adds a barrage of tests demonstrating the possible cases, most of which fail with current master.

Fix byte update flattening

---

.githooks/pre-commit
scripts/run_lint.sh

Follow-up to #433 as suggested by @peterschrammel.

Remove explicit "python" as cpplint.py is executable

---

regression/get_coverage.sh

This change fixes #440 there are two parts:
1. By default remove the temporary gcov files.
2. Remove remaining camel case in file and variable names.

Remove (by default) temporary gcov files created when running code coverage

---

regression/goto-instrument/argc-argv1/main.c
regression/goto-instrument/argc-argv1/test.desc
src/goto-instrument/Makefile
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-instrument/model_argc_argv.cpp
src/goto-instrument/model_argc_argv.h

Programs using argc and argv need to have these set up properly. This patch introduces an instrumentation achieving this.

goto-instrument --model-argc-argv: Explicitly initialise argc, argv

---

scripts/cpplint.py

These were causing a bunch of false positives that were making it hard to find real errors. Until there is time to fix them, just disable them.
Issues associated area:
https://github.com/diffblue/cbmc-testgen/issues/76
https://github.com/diffblue/cbmc-testgen/issues/75
https://github.com/diffblue/cbmc-testgen/issues/49

Commented out some false positive tests in the linting script

---

src/analyses/cfg_dominators.h
src/goto-programs/cfg.h

This previously assumed some internal specifics of goto_programt. This generalises it to allow the CFG graph to specify how to retrieve the start and end nodes or detect an empty program, and moves the details particular to goto_programt into its particular specialisation.
This allows us to use the generic dominators implementation on other control-flow graph representations.
This replaces #367 to address existing review comments and also bring the PR under my control since I'll be the one fixing any forthcoming review comments.

Generalise dominators template

---

src/java_bytecode/Makefile
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_convert_method_class.h
src/java_bytecode/java_local_variable_table.cpp

This PR replaces the existing simple local variable table code, which introduces a distinct variable per local variable table entry, with a simple control-flow analysis that merges table entries that flow into one another.
Recommend looking at each commit individually, as they introduce new functionality, use it, then factor into separate files.

Enhanced local variable table

---

src/cpp/cpp_template_args.h
src/cpp/cpp_typecheck.cpp
src/cpp/cpp_typecheck_expr.cpp
src/cpp/cpp_typecheck_fargs.cpp
src/cpp/cpp_typecheck_resolve.cpp
src/solvers/flattening/boolbv_get.cpp
src/solvers/flattening/boolbv_struct.cpp
src/solvers/flattening/flatten_byte_operators.cpp
src/solvers/prop/prop_conv.cpp
src/util/base_type.cpp
src/util/expr_util.cpp
src/util/std_code.h

Although USE_LIST is gone as of r3530, there are a number of cases where iterators are preferable over indexed access to elements.
This is a duplicate of #9 after restoring all links to the SVN.

Cleanup of operands() accesses

---

regression/Makefile
regression/cbmc-java/package_friendly1/test.desc

This fixes an errant Java test and enables the cbmc-java regression test directory for a general `make test` command (and therefore for continuous integration).
Test `package_friendly1` was fixed (tested for now-changed behaviour)
Test `monitorenter1` requires #458 to work properly.
The last two commits are the only ones unique to this PR; the rest will rebase away when #458 goes in.

Enable java tests

---

src/solvers/cvc/cvc_conv.cpp
src/solvers/cvc/cvc_conv.h
src/solvers/cvc/cvc_dec.cpp
src/solvers/cvc/cvc_prop.cpp
src/solvers/cvc/cvc_prop.h

Two main types of fixes:
- Simple fixes; mostly if statements being split onto 2 lines
- Breaking up `convert_expr` into a bunch of smaller functions as was over 600 lines. 
With the most up-to-date linting script (e.g. after #415 and #417 have been merged) this passes the linting check with 0 errors.

Fixing linting issues in solvers/cvc

---

src/java_bytecode/java_bytecode_convert_method_class.h
src/java_bytecode/java_bytecode_parse_tree.h
src/java_bytecode/java_bytecode_parser.cpp
src/java_bytecode/java_local_variable_table.cpp

This adds exceptional control flow to the control-flow graph used to calculate Java dominator trees.
This resolves occasional problems introduced in the Enhanced Local Variable Table patchset, where it wouldn't be able to find a common dominator for a variable use in a `try` and one in the corresponding `catch` block.
Required for test cmbc-java/LocalVarTable4 to pass.

Exception edges for live range analysis master

---

regression/cbmc-java/jar-file1/test.desc
regression/cbmc-java/jar-file2/test.desc

With cbmc-java regression tests enabled by default, the absence of optional JAR/zip file support should not cause regression tests to fail.

Make JAR/zip support optional in regression tests

---

src/analyses/flow_insensitive_analysis.cpp
src/cpp/cpp_typecheck_compound_type.cpp
src/goto-instrument/goto_program2code.cpp
src/goto-programs/goto_convert.cpp
src/goto-programs/goto_convert_functions.cpp
src/goto-programs/goto_convert_new_switch_case.cpp

The previous patch would make std_code consistent, but had failed to adjust uses of `code_returnt`.

fixup! Consistently resize instead of just reserving in codet classes

---

src/cbmc/bmc.cpp
src/goto-symex/goto_symex.h
src/goto-symex/symex_dereference.cpp
src/pointer-analysis/goto_program_dereference.h
src/pointer-analysis/value_set_dereference.cpp
src/pointer-analysis/value_set_dereference.h

#197 and diffblue/verification-engine-utils#173 showed that in some circumstances, goto-symex's value-set analysis can reach the conclusion that an integer may be cast to a pointer, and so generate a reference to the __CPROVER_memory symbol. This is invalid in Java however, since the symbol is not defined and of course Java cannot express dereferencing a non-pointer type.
The attached patch disables generation of __CPROVER_memory references when a Java-typed entry point is found. I couldn't provide a test case against master at this time however because the examples in both of the above bugs now succeed against master, presumably because value-set analysis has been improved and is harder to confuse into introducing a pointer-to-int cast.

Disable cprover memory for java

---

src/java_bytecode/java_bytecode_language.h
src/langapi/language_ui.cpp
src/util/language.h

Adds call to `get_language_options` to the language API. Prevents an
uninitialized bool error in the Java front-end.

get_language options to language API

---

src/goto-programs/Makefile
src/goto-programs/class_identifier.cpp
src/goto-programs/class_identifier.h
src/goto-programs/remove_virtual_functions.cpp

Part 2 of the remove virtual functions improvements (ready for merge now). This will be useful for other passes that inspect an object's dynamic clsid, such as the forthcoming lower-instanceof pass.

Factor class identifier extraction out of remove virtuals

---

src/java_bytecode/java_object_factory.cpp

fixes cases where super class fields are initialized with `null` which contradicts `ASSUME`
supersedes diffblue/cbmc-testgen#47
depends on #425

Fix nondet sublass init non null

---

src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/goto-programs/Makefile
src/goto-programs/remove_static_init_loops.cpp
src/goto-programs/remove_static_init_loops.h
src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_parse_tree.cpp
src/java_bytecode/java_bytecode_parse_tree.h
src/java_bytecode/java_bytecode_parser.cpp
src/util/irep_ids.txt

unwind loops in `<clinit>` for `#enum` times as heuristic to make static initialization of Java enums finish
requires #425 
[real diff](https://github.com/diffblue/cbmc/pull/460/commits/ed80984839d29de7e5dcfeeb7c4cf45b5bf70e04)

Java unwind enum static

---

src/util/irep_ids.txt
src/util/ssa_expr.cpp
src/util/ssa_expr.h

Previously these were derived from the full SSA ID by searching for the last character that can't feature in a C identifier. Unfortunately a period /can/ feature in a Java identifier (e.g. mypackage.myclass.myfunction). Alternatively we could just flip the #if test at ssa_expr.h:67, but there was apparently a performance motive to avoid this in the first place.

Keep SSA L1 IDs as an attribute

---

src/analyses/goto_check.h
src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/clobber/clobber_parse_options.cpp
src/clobber/clobber_parse_options.h
src/goto-analyzer/goto_analyzer_parse_options.cpp
src/goto-analyzer/goto_analyzer_parse_options.h
src/goto-diff/goto_diff_parse_options.cpp
src/goto-diff/goto_diff_parse_options.h
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-programs/show_goto_functions.h
src/symex/symex_parse_options.cpp
src/symex/symex_parse_options.h

This way if the help or command flag wants to change it can be done in one place. Also ensures that all programs that support the `--show-goto-functions` have it in the help output. Also ensures they all call the
correct function which means flags like `--json-ui` will work as expected.
There is probably a nicer way to structure the shared flags, since even with this approach the code of checking the flag is on and running the correct function is duplicated, but this at least makes the documentation and behaviour consistent across all the programs.

Replaced all instances of show-goto-functions with a define

---

src/java_bytecode/java_bytecode_convert_method.cpp

Commit 67f40196a0f206b0eabbef7081f33afa7f2fca1b accidentally reverted `java_bytecode_convert_methodt::variable` to an earlier version. This restores the version as of (https://github.com/smowton/cbmc/blob/find_scopes_for_anonymous_variables/src/java_bytecode/java_bytecode_convert_method.cpp).
Fixes failure of test cbmc-java/inferlexicalscope1

Do not add named vars to used_local_names

---

.travis.yml

We now have a separate Jenkins job for PRs that reports the erros. The rationale is that github status for a build is only "fail/pass" for travis and so it was not easily visible whether a fail was due to linter or actuall build problems.

CPPlint on travis will not produce error return code

---

src/cbmc/cbmc_parse_options.cpp
src/goto-programs/remove_complex.cpp
src/goto-programs/remove_vector.cpp
src/goto-symex/adjust_float_expressions.cpp
src/goto-symex/adjust_float_expressions.h
src/goto-symex/rewrite_union.cpp
src/goto-symex/rewrite_union.h
src/goto-symex/symex_clean_expr.cpp
src/path-symex/path_symex_state_read.cpp
src/symex/symex_parse_options.cpp

... and should not modify expressions unnecessarily!

Expression transformations for symbolic execution need only be done once

---

src/goto-programs/Makefile
src/goto-programs/remove_instanceof.cpp
src/goto-programs/remove_instanceof.h

This adds the remove-instanceof pass, which converts Java instanceof operations into explicit clsid compares. It isn't used yet, but the forthcoming PR (last in the series) will plumb it into the Java frontend.

Implement remove-instanceof

---

.githooks/pre-commit
scripts/cpplint.py

This also fixes the problem of failing to deduce the correct include guards.

Make the pre-commit hook report non-temporary path names

---

regression/goto-instrument/const-struct1/test.desc
regression/goto-instrument/const-struct2/main.c
regression/goto-instrument/const-struct2/test.desc
regression/goto-instrument/const-struct3/main.c
regression/goto-instrument/const-struct3/test.desc
regression/goto-instrument/const-union1/main.c
regression/goto-instrument/const-union1/test.desc
regression/goto-instrument/volatile-struct1/main.c
regression/goto-instrument/volatile-struct1/test.desc
src/ansi-c/c_typecheck_type.cpp

Issue: #355, https://github.com/diffblue/cbmc-toyota/issues/21 [private]
When dealing withs structs (and unions) we replace the type with a symbol for that type (that may or may not be new). However, if a struct is declared, we still need to track any qualifiers (e.g. a variable that
is introduced as a const struct).
Changed the test demonstrating this to core and extended the testing to cover other related situations.

Keep track of qualifiers for structs and unions

---

src/util/cmdline.h

Gave read of uninitilized Boolean value. Just a cleanup, no effect apart from
observation via UB check.

specify initial values for Boolean in struct optiont

---

.gitignore

Ignore some more generated files from the regressions folder (.gb files and all the log files. Also removed some redundant lines that are now covered by the **/*.log rule. Added the clobber binary and moved the
test-bigint binary to the binaries section.

Additions to the gitignore

---

src/ansi-c/ansi_c_typecheck.cpp
src/ansi-c/c_typecheck_code.cpp

c_typecheck_baset contains the method `start_typecheck_code()` which is not
called for `ansi_c`, only for `cpp`. This method initializes three Boolean
values:
```
bool break_is_allowed;
bool continue_is_allowed;
bool case_is_allowed;
```
This patch adds a call to `start_typecheck_code()` to `ansi_c`, too.
The error was observed in `ansi_c/for_scope1`.

initialize Boolean values in c_typecheck_baset

---

src/goto-programs/format_strings.h

This lead to uninitialized read of length_modifier and representation. While
probably not critical, as the respective switches contain a default branch and
the compiler seems to allow integral values outside the enum range.

add explicit undef value to format string enums

---

src/java_bytecode/java_bytecode_parse_tree.cpp
src/java_bytecode/java_bytecode_parse_tree.h
src/java_bytecode/java_bytecode_parser.cpp

This adds the initialization of the `is_abstract` and `is_enum` Boolean values
to the Java class file parser. It also adds setting the value of `is_abstract`
which wasn't done before and could lead to undefined behaviour as an unitialized
bool was read in `std::swap(other.is_abstract, is_abstract)`.

read ACC_ABSTRACT attribute in Java class files

---

regression/cbmc/Function5/test.desc
regression/cbmc/Malloc23/main.c
regression/cbmc/Malloc23/test.desc
regression/cbmc/Pointer_byte_extract5/test.desc
src/analyses/goto_check.cpp
src/pointer-analysis/value_set_dereference.cpp
src/util/pointer_predicates.cpp
src/util/pointer_predicates.h

This is a recreation of an old orphaned, stalled pull request. Fixes https://github.com/diffblue/cbmc/issues/239 -- see that issue for more details.

Improve array bounds checks

---

src/java_bytecode/java_bytecode_typecheck.cpp
src/java_bytecode/java_bytecode_typecheck.h

The string literal uniqueing tables only work if they can see every string in the program, and if multiple .class files are specified on the command-line, multiple java_bytecode_typecheckt instances are created. Literal symbol creation would then fail if the two classes used matching literals. Note this does not apply to classes loaded on demand or from a JAR file, which *do* share a typecheckt instance with their parent.
This averts the immediate problem, but subsequent changes worth considering:
1. Give languaget a pointer back to some new class (say `java_language_globalt`) that houses state global to all Java frontend instances, and which cleans up after all Java frontends have gone away.
2. Since the Java frontend's demand-loads classes, *sharing* an instance of `java_languaget` in …

Make string literal tables global

---

src/java_bytecode/expr2java.cpp

to_integer returns true in case of error. The contrary was assumed in
convert_constant().

Correct return value test of to_integer

---

src/util/json.h

While working on JSON reading I discovered incorrect usage of the inline keyword.
See http://en.cppreference.com/w/cpp/language/inline for why this is the case, especially the second paragraph:
A function defined entirely inside a class/struct/union definition, whether it's a member function or a non-member friend function, is implicitly an inline function.

Fixed use of inline

---

regression/goto-instrument/unwind-zero-unwind3/main.c
regression/goto-instrument/unwind-zero-unwind3/test.desc
src/goto-instrument/unwind.cpp

This fixes a bug for when unwinding a loop zero times.

Fix adjustment of goto targets in the loop unwinder

---

src/util/expr.cpp

The `is_true()` / `is_false()` functions in `exprt` currently support
only the `ID_bool` type. In Java, Boolean values are represented as
`ID_c_bool` due to the internal JVM usage of integers. Adding this
support here seems easier than having special treatment in
`java_bytecode`.
cf. #221

direct support for ID_c_bool in exprt

---

src/java_bytecode/java_bytecode_typecheck_expr.cpp

When dealing with opaque (unelaborated) classes, this infers
that a particular class or superclass must have a particular
field when the source program assumes their presence (i.e.
when there is an ((A*)a)->x reference and we don't yet know that
a field named 'x' exists). This feeds into opaque stub generation,
which can use the inferred type descriptor to create appropriate
object initialisers in stub functions.

Add implied fields to classes

---

src/java_bytecode/java_bytecode_typecheck_expr.cpp

c1a34930effd3c9886ab20055787fe75d44d6d3f accidentally disabled use of the escaped_string_literal_count map. This restores the original behaviour and adds a comment to dissuade repeating the same mistake.
Problem was introduced in https://github.com/diffblue/cbmc/pull/425

Restore string literal symbol name escaping

---

src/util/irep_hash_container.cpp
src/util/irep_hash_container.h

The return value of `inline size_t operator()(const packedt &p) const` is
`size_t`, the contents of `packedt` is `unsigned`. The result is computed as the
XOR of all contents of the `packedt` vector, shifted to the left `n` times,
where `n` is the index in the `packedt`. Shifting for more than the bits of the
type in `packedt` (here unsigned) is undefined behavior.
This patch removes the UB by i) casting the `unsigned` to `size_t` which is
bigger (64 vs 32 bits) in LP64 and LLP64 and by ii) stopping the loop/shifting
at the bitsize of `size_t`, after which only zeroes would be XORed to the
result.
The erroneous behaviour was observed in `ansi-c/extern1` regression test.

fix shift overflow in irep_hash_container

---

src/cbmc/Makefile
src/cbmc/bmc.cpp
src/cbmc/bmc.h
src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/cbmc/symex_bmc.cpp
src/cbmc/symex_bmc.h
src/cbmc/symex_coverage.cpp
src/cbmc/symex_coverage.h

These patches add a new option --symex-coverage-report foo.xml to CBMC, where foo.xml follows the specification of the [Cobertura](http://cobertura.github.io/cobertura/) tool. This output format seems to be understood and/or generated by a number of other tools, and specifically integrates nicely with Jenkins as shown, e.g., [here](http://jenkins-le-guide-complet.github.io/html/sect-first-steps-metrics.html).

Cobertura-formatted reports of symex coverage

---

regression/ansi-c/function_return1/test.desc
regression/ansi-c/struct6/test.desc
regression/ansi-c/struct7/test.desc
src/ansi-c/c_typecheck_type.cpp
src/goto-cc/armcc_mode.cpp
src/goto-cc/armcc_mode.h
src/goto-cc/as_mode.cpp
src/goto-cc/as_mode.h
src/goto-cc/cw_mode.cpp
src/goto-cc/cw_mode.h
src/goto-cc/gcc_mode.cpp
src/goto-cc/gcc_mode.h
src/goto-cc/goto_cc_mode.cpp
src/goto-cc/goto_cc_mode.h
src/goto-cc/ms_cl_mode.cpp
src/goto-cc/ms_cl_mode.h
src/util/cout_message.cpp
src/util/cout_message.h

This adds error messages to goto-cc that mimic those produced by gcc.

gcc-style error messages

---

regression/cbmc-concurrency/dirty_local1/main.c
regression/cbmc-concurrency/dirty_local1/test.desc
regression/cbmc-concurrency/dirty_local2/main.c
regression/cbmc-concurrency/dirty_local2/test.desc
src/goto-symex/goto_symex_state.cpp
src/goto-symex/goto_symex_state.h
src/goto-symex/memory_model_pso.cpp
src/goto-symex/memory_model_sc.cpp
src/goto-symex/memory_model_tso.cpp
src/goto-symex/partial_order_concurrency.cpp
src/goto-symex/partial_order_concurrency.h
src/goto-symex/symex_decl.cpp
src/goto-symex/symex_function_call.cpp
src/goto-symex/symex_goto.cpp
src/goto-symex/symex_main.cpp
src/goto-symex/symex_start_thread.cpp

Also make goto_symex_statet decide what is shared, no needless (and now
broken) wrapper functions. Fixes #304

Treat local dirty variables as shared ones

---

src/cegis/Makefile

Fixes: 910ca64 ("cbmc --symex-coverage-report: Cobertura-compatible coverage output")

Include cbmc/symex_coverage in CEGIS build

---

src/goto-programs/goto_program_template.h
src/goto-programs/remove_static_init_loops.cpp
src/solvers/prop/aig.cpp

Fixes for #531 and #532. These are untested.

VisualStudio build fixes

---

scripts/cpplint.py

Add a new output format to cpplint (--output=sed) that emits a shell script containing sed commands that will fix many of the errors, one line at a time. An example of the fixes this produces is coming in another PR.

cpplint sed output format

---

.travis.yml
scripts/filter_lint_by_diff.py
scripts/run_lint.sh
scripts/travis_lint.sh

This replaces the linter filter with a Python version better able to handle large diffs.
Changes:
* Replaces git-blame + regex matching with git-diff + Python-unidiff (circumvents too-many-commits -> argument-list-too-long problem found by @mgudemann)
* Uses `git merge-base` to find an appropriate grounds for comparison to give an effective one-way diff
* Can compare against current working tree
* Can compare against a non-master PR target.

Better linter filtering

---

src/java_bytecode/java_bytecode_typecheck.cpp
src/java_bytecode/java_bytecode_typecheck.h
src/java_bytecode/java_bytecode_typecheck_expr.cpp

Before we squashed identifier-illegal characters and used a map to work around the ensuing identifier clashes (e.g. Hello? and Hello! both squash to Hello_ so now one must be renamed).
This switches to an encoding scheme: _ -> __, other unprintable character -> _xx where xx is a hex byte.

Switch to stateless Java string escaping

---

scripts/filter_lint_by_diff.py

git-diff when a file has been removed diffs against /dev/null instead of the usual pattern `b/some/path/to/file.cpp`. This change avoids asserting a "b/" prefix in that case.

Fix lint filter against deleted files. Fixes #563

---

regression/goto-instrument/is-threaded1/main.c
regression/goto-instrument/is-threaded1/test.desc
src/analyses/is_threaded.cpp
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h

This simplifies is_threadedt and fixes an issue where the is_threaded property was not propagated back to function call sites.
@tautschnig: Please check if this looks reasonable to you.

Fix for is_threadedt

---

src/cbmc/cbmc_solvers.cpp
src/cbmc/cbmc_solvers.h

This is a new variant of #528, doing a complete clean up into one class that holds all objects.

cleanup of CBMC solver factory

---

src/Makefile

Without this patch, calling "make clean" fails, because make
tries to call "make clean" in the aa-symex directory as well.
By removing aa-symex from the DIRS variable, this problem is fixed.
Fixes: cleanup aa-path-symex and aa-symex
Solves issue:
https://github.com/diffblue/cbmc/issues/576

Remove aa-symex from DIRS variable in Makefile

---

.travis.yml
src/util/unicode.cpp
src/util/unicode.h

_(Description by @forejtv:)_ This is successor of https://github.com/diffblue/cbmc/pull/372 after @smowton took the PR over. For convenience, this is the original PR description, see that PR for some discussion and context:
Adds functions to `util/unicode.cpp` to convert from utf8 strings to utf16, both for little and big endian encodings and a function to pretty print utf16 characters in ascii.
These conversions are useful for the string refinement because utf16 is used by java.
Note that codecvt does not come automatically with old version of gcc, so I saw compilation problems with gcc-4.8 (Ubuntu 16.04), but none with gcc-6.

utf8 to utf16 conversion and utf16 to ascii

---

src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_class.h
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_bytecode_language.h
src/java_bytecode/java_bytecode_typecheck.cpp
src/java_bytecode/java_bytecode_typecheck.h
src/java_bytecode/java_bytecode_typecheck_expr.cpp

When string-refinement is enabled, we define what java.lang.String objects are supposed to contains, and we affect this kind of objects for string literals.
Replaces #491. Depends on #541.

String refine java bytecode

---

src/goto-programs/goto_program.h

This allows locationt et al to be used in unordered_map/set.

SSS: Add goto-program instruction iterator hasher

---

src/java_bytecode/java_bytecode_convert_method.cpp

The checkcast instruction should always return the pointer it checked, even when we're not generating an assert in the case that it failed.
Will make an upstream version of this since it's a fix.

SSS: Java checkcast: fix stack when check disabled

---

src/ansi-c/ansi_c_language.cpp
src/ansi-c/ansi_c_language.h
src/cpp/cpp_language.cpp
src/cpp/cpp_language.h
src/goto-programs/get_goto_model.cpp
src/goto-programs/get_goto_model.h
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_bytecode_language.h
src/jsil/jsil_language.cpp
src/jsil/jsil_language.h
src/langapi/language_ui.cpp
src/langapi/language_ui.h
src/util/language.cpp
src/util/language.h
src/util/language_file.cpp
src/util/language_file.h

The `_start` routine can be huge and time-consuming to generate for our target applications, and we never need it. Might want to add a clean interface for a driver program to tell language-files it doesn't want `_start`, then this could go upstream.

SSS: Make _start optional

---

src/cbmc/cbmc_parse_options.cpp
src/util/overlay_map.h

This is a std-map-like container that can act as a writable layer atop another map, intended to use when a sequence or graph of maps only differ sparsely, like abstract interpretation domains for a sequence of program points.
This is on the fence to improve and suggest to master, or kill and replace with @danpoe's solution to a similar problem.

SSS: Add overlay-map

---

src/analyses/static_analysis.cpp
src/analyses/static_analysis.h

Static analysis is marked obsolete upstream, but also still the basis for value-set analysis. This adds some basic hooks for a subclass to: (a) provide behaviour at a function stub, (b) get an ordinary callback even on recursive calls, (c) count transform operations. It also enables printing instructions in domain dumps, which matches the replacement `ai.h`'s behaviour.

SSS: static analysis tweaks

---

src/java_bytecode/java_bytecode_convert_method.cpp

The checkcast instruction should always return the pointer it checked, even when we're not generating an assert in the case that it failed.

Java checkcast: fix stack when check disabled

---

src/goto-analyzer/goto_analyzer_parse_options.cpp
src/goto-programs/get_goto_model.cpp
src/goto-programs/get_goto_model.h
src/symex/symex_parse_options.cpp

We already have get-language-options in CBMC to configure the Java frontend specifically. Other driver programs that use get-goto-model should call it too.
This belongs upstream too, will create a PR against master for this as well.

SSS: Call get_language_options from get_goto_model

---

src/util/expr_util.cpp
src/util/expr_util.h

This looks through member expressions.

SSS: Add get-underlying-object utility

---

src/util/irep_ids.txt

Until we figure out an alternative mechanism, it's only really practical for irep IDs to be added in the support branch.

SSS: Add irep IDs

---

src/util/simplify_expr.cpp
src/util/simplify_expr_class.h

Normally it will eliminate casts from one struct type to another
if they have like members, but this leads to type errors in
languages like Java where they cannot be used interchangeably
unless they also have a subtype relationship.

SSS: Keep identical structs

---

src/analyses/call_graph.cpp
src/analyses/call_graph.h

These extend `call_grapht` with some basic is-(transitive)-child and topological sorting functions.

SSS: Call graph utilities

---

scripts/cpplint.py

The reason for `<regex>` being discouraged seems to be a preference for an
external library within Google:
https://github.com/google/styleguide/issues/194

remove `<regex>` from unapproved headers in cpplint

---

src/add_shlwapi.inc
src/config.inc

This should link shlwapi.dll, fixing the AppVeyor failure currently happening on the SSS branch.

SSS: Windows build fix

---

scripts/cpplint.py

Fix 3 more error types.
Add some commented out fixes for changes that affect line numbers. These break other fixes later in the same file - to use them, fixes will need to be applied in reverse order.

cpplint sed format improvements

---

src/analyses/cfg_dominators.h

There are a couple of linting failures but these are due to a slightly over-zealous standard IMHO.
@danpoe This is one of the features I added at Toyota and we need for the next release.

Fix cfg dominator top

---

.travis.yml
regression/cpp/enum8/test.desc
scripts/minisat-2.2.1-patch
src/util/memory_info.cpp

By applying these changes we are able to compile cbmc code and run successfully all tests in alpine linux.

Support for non-glibc linux which use musl-libc

---

src/pointer-analysis/value_set_analysis.h

The non-virtual call is hidden by a like-named virtual; calling
via a base-class reference like this avoids the need for all
subclasses to explicitly forward the method.

Call get_value_set via a base-class reference

---

src/goto-instrument/code_contracts.cpp
src/goto-programs/goto_clean_expr.cpp
src/goto-programs/goto_convert.cpp
src/goto-programs/goto_convert_class.h
src/goto-programs/remove_function_pointers.cpp
src/goto-programs/remove_instanceof.cpp
src/java_bytecode/java_object_factory.cpp
src/java_bytecode/java_object_factory.h
src/util/Makefile
src/util/fresh_symbol.cpp
src/util/fresh_symbol.h

Code to generate a fresh-named aux symbol was duplicated in quite a few places

Factor out fresh symbol generation

---

src/java_bytecode/java_entry_point.cpp

This depends on #506 
Real diff: https://github.com/cristina-david/cbmc/compare/exception-handling...cristina-david:tag-exceptional-return-as-output?expand=1

Tag exceptional return as output

---

regression/goto-instrument/slice02/test.desc
regression/goto-instrument/slice14/test.desc
src/cbmc/cbmc_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.cpp

Invoked full_slicer after generic property instrumentation so that
it can properly slice the program w.r.t. the assertion. Replaced returns
from goto functions in goto_instrument_parse_options, as done similarly
in cbmc_parse_options

Fixed test cases slice02 and slice14 from goto-instrument regression

---

scripts/filter_lint_by_diff.py

Sometimes the diff file would contain a unicode character. Since we were opening the file, this meant that unidiff was reading the file in the wrong format. By letting unidiff handle reading the file we slightly simplify the code and fix this problem.

Fixed crash on non-ascii diff

---

src/goto-programs/show_symbol_table.h

This caused this to not compile if included before whatever brings in goto_modelt.

Missing forward declaration

---

src/pointer-analysis/value_set_analysis_fi.cpp
src/pointer-analysis/value_set_analysis_fivr.cpp
src/pointer-analysis/value_set_analysis_fivrns.cpp

Profiling found these unnecessary loops in the pointer analysis.  They have a big impact on larger code bases.
@danpoe This is another branch you'll need for the next delivery.

Pointer analysis tidy

---

regression/goto-instrument/inline_13/main.c
regression/goto-instrument/inline_13/test.desc
regression/goto-instrument/inline_14/main.c
regression/goto-instrument/inline_14/test.desc
regression/goto-instrument/inline_15/main.c
regression/goto-instrument/inline_15/test.desc
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-programs/goto_inline.cpp
src/goto-programs/goto_inline.h
src/goto-programs/goto_inline_class.cpp
src/goto-programs/goto_inline_class.h

This adds an option ``--no-caching`` to goto-instrument which disables the caching of intermediate results when doing transitive inlining (currently used by ``--function-inline``). This is to improve memory consumption on the codebase of an industrial partner.

Option to disable caching for inlining

---

src/util/file_util.cpp

Give more meaningful message when crash because path doesn't exist

Handle path doesn't exist in fileutl_absolute_path

---

src/ansi-c/ansi_c_language.cpp
src/ansi-c/ansi_c_language.h
src/ansi-c/expr2c.cpp
src/ansi-c/expr2c_class.h
src/cpp/cpp_language.cpp
src/cpp/cpp_language.h
src/cpp/expr2cpp.cpp
src/cpp/expr2cpp_class.h
src/java_bytecode/expr2java.cpp
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_bytecode_language.h
src/jsil/expr2jsil.cpp
src/jsil/expr2jsil_class.h
src/jsil/jsil_language.cpp
src/jsil/jsil_language.h
src/langapi/language_util.cpp
src/langapi/language_util.h
src/langapi/pretty_printer.h
src/util/language.h

Despite its name, expr2c is the de facto global default pretty-printer.
This allows an extension module to register a handler for expr types
that expr2c cannot do by itself.

Add simple pretty-printer extension mechanism

---

scripts/cpplint.py
scripts/filter_lint_by_diff.py
scripts/run_lint.sh
src/util/file_util.cpp

Merged master to get update to delete_directory and linter

Security scanner support

---

src/goto-programs/string_refine_preprocess.cpp
src/goto-programs/string_refine_preprocess.h
src/java_bytecode/java_bytecode_convert_class.cpp
src/solvers/refinement/string_constraint.h
src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_code_points.cpp
src/solvers/refinement/string_constraint_generator_comparison.cpp
src/solvers/refinement/string_constraint_generator_concat.cpp
src/solvers/refinement/string_constraint_generator_constants.cpp
src/solvers/refinement/string_constraint_generator_indexof.cpp
src/solvers/refinement/string_constraint_generator_insert.cpp
src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_constraint_generator_testing.cpp
src/solvers/refinement/string_constraint_generator_transformation.cpp
src/solvers/refinement/string_constraint_generator_valueof.cpp
src/solvers/refinement/string_refinement.cpp
src/solvers/refinement/string_refinement.h
src/util/irep_ids.txt

Fast-forward of #646 to `test-gen-support` branch.
No dependencies.

Corrections to the string solver

---

src/config.inc
src/util/dstring.cpp
src/util/dstring.h
src/util/file_util.cpp
src/util/file_util.h
src/util/irep.cpp
src/util/irep.h
src/util/serializer.h

This adds a generic serialization framework that is used by summary virtualization in the security scanner.
It allows for targets including storage as JSON or using a database server.
It uses a non-virtual serialize method (through the use of templates) that avoids adding size to the objects to be serialized.
A trade-off was the choice to use single function serialization (rather than separate load/save functions). This minimises the impact on classes to be serialized but does sometimes cause issues as const objects can't naively be serialized out.
make_valid_filename has been added. This is for use in JSON serialization. While this serialization implementation is not included in the CBMC repository, this repository seems the right place for that function.
The serialization of irept in …

Added serialization of irept and dstringt

---

src/ansi-c/expr2c.cpp

Thought I'd made a mistake when I got `return irep("nil")` in the symbol table output-- turns out the C pretty-printer just never got updated when `code_returnt` started using a nil irep to represent return-without-value. This cleans it up.

Correct pretty-printing of code_returnt

---

src/goto-programs/string_refine_preprocess.cpp
src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_refinement.h

Corrections on PR 675

---

src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/goto-programs/show_goto_functions.h
src/symex/symex_parse_options.cpp
src/symex/symex_parse_options.h

The default behaviour of CBMC for the options --show-goto-functions,
--show-properties and --cover is to consider all functions. This
is particularly annoying for --cover where coverage goals are
reported from functions that are not reachable from the entry point.
Also, --show-reachable-properties has been introduced in the past
to hide such properties.
We could change the default behaviour to slicing away everything
that is not reachable from the entry point. However, this would
require an extra option to be able to view functions and properties
that are not reachable.
This PR preserves the default behaviour and enables focussing
the output of --show-goto-functions --show-properties and --cover
on reachable functions using --reachable-functions.
The option --show-reachable-properties …

Cover (and others) for reachable functions only

---

src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/cbmc/cbmc_solvers.cpp
src/cbmc/cbmc_solvers.h
src/goto-programs/Makefile
src/java_bytecode/java_bytecode_language.cpp
src/solvers/Makefile
src/util/Makefile

Fast-forward of #429 on test-gen-support branch.
Depends on #675.

String refine option

---

src/analyses/call_graph.cpp
src/analyses/call_graph.h

There are 3 updates:
1) Added mapping from edges of the call-graph to particular instructions in the caller GOTO programs, where the calls are performed.
2) Added new functions find_direct_or_indirect_callees_of_function and find_nearest_common_callees.
3) Clean up output_dot.

Extension of the call-graph and call-graph-based algorithms

---

regression/goto-instrument/slice22/main.c
regression/goto-instrument/slice22/test.desc
regression/goto-instrument/slice23/main.c
regression/goto-instrument/slice23/test.desc
src/goto-instrument/full_slicer.cpp
src/pointer-analysis/value_set_fi.cpp

Do not slice away array_copy expressions during the implicit call in the full-slicert class. Added two test cases into goto-instrument regression for checking array_copy expressions using the full-slice option.

consider array_copy expressions in the full-slice 

---

COMPILING

The current instructions don't work for compiling on RedHat and need a small tweak to work for Ubuntu. I have tested these instructions on RedHat 7 and Ubuntu 16.10.

Updates to compiling instructions for GCC 6

---

src/analyses/goto_check.cpp
src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/cbmc/symex_coverage.cpp
src/goto-instrument/count_eloc.cpp
src/goto-instrument/cover.cpp
src/goto-programs/builtin_functions.cpp
src/goto-programs/graphml_witness.cpp
src/util/source_location.h

This PR includes a clean-up of various checks whether something is a built-in.

No-assertions should not affect assertions in built-ins

---

src/config.inc
src/util/file_util.cpp

This eliminates our one Boost runtime dependency, meaning we can now build by packaging header dependencies only.

Replace boost dependency with simple mkdir -p implementation

---

src/langapi/language_ui.cpp
src/langapi/language_ui.h

Identifiers containing a double-underscore are reserved for the implementation.

Remove reserved identifier

---

src/cbmc/cbmc_parse_options.cpp
src/clobber/clobber_parse_options.cpp
src/goto-analyzer/goto_analyzer_parse_options.cpp
src/goto-diff/goto_diff_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-programs/link_to_library.cpp
src/musketeer/musketeer_parse_options.cpp
src/symex/symex_parse_options.cpp

Display the architecture information if the user intends to add the CPROVER library for code instrumentation.

kept consistency between parse options of cbmc and goto-instrument tools for link_to_library call

---

regression/goto-instrument/slice01/test.desc
regression/goto-instrument/slice13/main.c
regression/goto-instrument/slice13/test.desc
regression/goto-instrument/slice16/test.desc

Enabled test cases slice01, slice13, and slice16 in the goto-instrument regression
suite after fixes related to commits 27227cc and 211cb90.

Enabled test cases in goto-instrument after fixes in the full-slice

---

src/java_bytecode/java_bytecode_language.cpp

Symbols can be missing at this stage because they would be introduced during
typechecking when it notices they are undefined, which happens if the type
they were defined on is missing.

Tolerate missing symbols in gather_needed_globals. Fixes #620

---

regression/ansi-c/static_inline1/main.c
regression/ansi-c/static_inline1/test.desc
regression/ansi-c/static_inline2/main.c
regression/ansi-c/static_inline2/test.desc

There is a problem with `cbmc` with how it handles `static inline` qualified functions. If we include a main function, and run `cbmc` without the `--function` parameter, so that it defaults to main, it converts the program without any issues. 
On the other hand, if we pass it a file without a main method in it, and call it with `--function fun`, then it will result in a `CONVERSION ERROR`.
This pull request contains tests to demonstrate that.

Added tests that demonstrate the issue with static inline c functions.

---

src/analyses/reaching_definitions.h
src/java_bytecode/bytecode_info.cpp
src/java_bytecode/java_bytecode_convert_method.cpp
src/util/std_types.h
src/xmllang/graphml.h

Removes a few `const`s on types which will always be returned by value, fixes an integer-size-comparison warning, and zero-initialises all fields of a struct in bytecode_info.cpp

Fix really pedantic compiler errors

---

CHANGELOG
regression/cbmc/Pointer_byte_extract9/main.c
regression/cbmc/graphml_witness1/test.desc
src/cbmc/cbmc_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/solvers/flattening/boolbv_floatbv_op.cpp
src/solvers/floatbv/float_utils.cpp
src/symex/symex_parse_options.cpp
src/util/irep.h
src/util/json_irep.cpp
src/util/rename_symbol.cpp

This is a collection of 10 mutually unrelated patches that mostly just fix/follow-up recently merged bits.

Near-release cleanup

---

src/goto-programs/interpreter.cpp
src/goto-programs/interpreter_class.h
src/goto-programs/interpreter_evaluate.cpp
src/util/sparse_vector.h

This allows large address reservations for unbounded-sized
objects, with actual cells allocated on demand.
Unbound objects get allocated 2^32 address space each (of a 2^64 sized space)
using the sparse-vector memory representation to keep the actual
storage requirements sensible.

Interpreter sparse memory

---

src/util/json_expr.cpp

Port JSON pointer output fix

---

src/goto-programs/goto_trace.h
src/goto-programs/json_goto_trace.cpp
src/goto-symex/build_goto_trace.cpp

hide variable assignments related to dynamic_object[0-9], dynamic_[0-9]_array, and CPROVER internal functions (e.g., __CPROVER_initialize). This PR fixes diffblue/test-gen#20.

set internal field in specific variables in the counterexample trace for test-gen-support

---

.gitignore
.travis.yml
src/Makefile
src/common

This should level the Boost environment across platforms.

Switch to using Boost header-only tarball

---

doc/html-manual/cover.shtml
doc/html-manual/pid_test_suites.xml

- adjusted the command line for the pid controller case study with a better look output test suites
- added the complete output from CBMC to the tutorial

adjusted the command line options for the pid controller case study

---

src/pointer-analysis/value_set.cpp
src/pointer-analysis/value_set.h
src/pointer-analysis/value_set_fi.cpp
src/pointer-analysis/value_set_fi.h
src/pointer-analysis/value_set_fivr.cpp
src/pointer-analysis/value_set_fivr.h
src/pointer-analysis/value_set_fivrns.cpp
src/pointer-analysis/value_set_fivrns.h
src/util/std_expr.cpp
src/util/std_expr.h

Removed the `dynamic_object_exprt`'s `instance()` methods and
replaced the usages using `set_location_number()`.
Added the `dynamic_object_id_sett` data structure into the
`value_sett` class. It is used as `expr_sett` but only for
dynamic-objects.

Removed the dynamic_object_exprt's instance()

---

src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_class.h
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_convert_method.h
src/java_bytecode/java_bytecode_convert_method_class.h
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_bytecode_language.h

This was not visible from the outside and therefore could not be set.
This closes #645.

Remove the disable-runtime-checks flag for Java

---

regression/cbmc-concurrency/trace1/main.c
regression/cbmc-concurrency/trace1/test.desc
src/goto-symex/build_goto_trace.cpp

Traces had been cut off at the failing assertion without considering steps
performed in threads with a higher thread id. The behaviour of --stop-on-fail
was correct in this regard. The trace trimming must only be performed after
re-ordering of steps according to their time stamps.

Fix concurrent traces generated via --trace

---

.travis.yml

All jobs now have ccache enabled, which means that subsequent compilation should be able to reuse the compiled files, and thus the job running time should be faster.
As part of the above, travis.yml needed to be restructured, in particular:
* instead of running the compilation and tests as one command, the commands are split
* cegis etc. compilation takes place before the tests are run.
While restructuring the travis.yml file, I also set cpplint as a failable job. This does not improve performance, just the output readability.

Improve Travis performance

---

.travis.yml
regression/goto-analyzer/constant_propagation_01/test.desc
regression/goto-analyzer/constant_propagation_02/test.desc
regression/goto-analyzer/constant_propagation_03/test.desc
regression/goto-analyzer/constant_propagation_04/test.desc
regression/goto-analyzer/constant_propagation_05/test.desc
regression/goto-analyzer/constant_propagation_06/test.desc
regression/goto-analyzer/constant_propagation_07/test.desc
regression/goto-analyzer/constant_propagation_09/test.desc
regression/goto-analyzer/constant_propagation_10/test.desc
regression/goto-analyzer/intervals1/test.desc
regression/goto-analyzer/intervals3/test.desc
regression/goto-analyzer/intervals5/test.desc
regression/goto-analyzer/intervals9/test.desc

This PR fixes problems introduces by recent merges, namely:
* Travis did not work due to missing parentheses
* Even if Travis worked, it would be very slow thanks to debug builds and subsequent tests using debug binary
* Some tests did not pass.

Fix Travis and test problems on master

---

CHANGELOG
src/goto-analyzer/goto_analyzer_parse_options.cpp
src/goto-analyzer/goto_analyzer_parse_options.h
src/goto-analyzer/unreachable_instructions.cpp
src/goto-analyzer/unreachable_instructions.h
src/goto-instrument/Makefile
src/goto-instrument/call_sequences.cpp
src/goto-instrument/call_sequences.h
src/goto-instrument/count_eloc.cpp
src/goto-instrument/count_eloc.h
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-instrument/undefined_functions.cpp
src/goto-instrument/undefined_functions.h

This is really just a single commit on top of #730, which should thus be reviewed and merged first.

goto-instrument: Replace calls to undefined functions by assume(false)

---

src/goto-symex/symex_goto.cpp

This pattern occurs in some SV-COMP benchmarks, but may also appear as
busy-wait loops in realistic systems.
This is another commit from #363.

Turn "label: goto label;" or "while(cond);" into assume

---

src/goto-analyzer/goto_analyzer_parse_options.cpp
src/goto-programs/get_goto_model.cpp
src/goto-programs/get_goto_model.h
src/symex/symex_parse_options.cpp

`get_language_options` is called from `cbmc_parse_options`. It should be called by other driver programs (which use get-goto-model) too; otherwise the Java frontend's (e.g.) skip-runtime-checks parameter remains uninitialised.

Call get_language_options from get_goto_model

---

src/cbmc/symex_bmc.cpp
src/cbmc/symex_bmc.h
src/cbmc/symex_coverage.cpp
src/cbmc/symex_coverage.h
src/goto-programs/remove_returns.cpp
src/goto-programs/remove_returns.h
src/goto-symex/goto_symex.h
src/goto-symex/goto_symex_state.h
src/goto-symex/symex_goto.cpp

The coverage reporting introduced in 910ca64e9 had some precision bugs and was not reporting branch coverage properly.

Coverage-report fixes

---

regression/cbmc/graphml_witness1/test.desc
src/cbmc/symex_coverage.cpp
src/cegis/invariant/fitness/concrete_fitness_source_provider.cpp
src/cegis/jsa/genetic/jsa_source_provider.cpp
src/goto-instrument/cover.cpp
src/goto-programs/goto_functions_template.h
src/goto-programs/show_goto_functions_json.cpp
src/goto-programs/show_goto_functions_xml.cpp
src/util/irep_ids.txt

While identifiers starting with _ (or __ ?) are reserved according to the C standard,
people nevertheless use them. Using __CPROVER_start will make collisions less
likely.
Includes cleanup so that, outside cegis, there is exactly one point where this
name is spelled out.

Rename _start to __CPROVER_start

---

src/goto-programs/builtin_functions.cpp
src/goto-programs/graphml_witness.cpp

These are the patches to support SV-COMP rules as found in #363.

SV-COMP support patches (from #363)

---

.travis.yml

After standardisation and release of [diffblue/cbmc-builder](https://github.com/diffblue/cbmc-builder), we should use versioned number of container so change to new version will be under control (currently we always fetch `latest`).

Use versioned container of Alpine Linux.

---

regression/goto-analyzer/approx-const-fp-array-variable-invalid-cast-const-fp/test.desc
src/cbmc/symex_bmc.cpp

This fixes problems arising from recent merges:
* problem from one of `_start` not being renamed.
* failing test (huge thanks to @thk123 for help on this)

Fix broken master

---

src/java_bytecode/Makefile
src/java_bytecode/character_refine_preprocess.cpp
src/java_bytecode/character_refine_preprocess.h

This processing of java method calls is meant to replace simple
methods of the Character Java by expressions on characters.
About 60% of the library is supported, but for some of this
methods are limited to ASCII characters.
This is meant to be run in conjunction with the string refinement so
it is called if the string-refine option is activated.

Adding conversion for functions of the Java Character library

---

src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/cbmc/cbmc_solvers.cpp
src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_concat.cpp
src/solvers/refinement/string_constraint_generator_insert.cpp
src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_refinement.cpp
src/solvers/refinement/string_refinement.h
src/util/string_expr.h

This replaces #695
This adds the option --string-max-length to the string solver, this constrains all the strings to be smaller than the maximal length. This shouldn't affect much the performance of the decision procedure but may be necessary for obtaining concrete traces (when the --trace option is activated).
I also added the options --string-non-empty to constrain the nondet strings to have length at least 1 (to avoid obtaining counter-example that concatenates the empty string two times, which is not very interesting), and --string-printable to constrain strings to contain only characters in the range between (space, U+0020) and ~ (tilde, U+007E). making the example nicer than a sequence of null characters.
This also fixes a couple of bugs in the solver.
This corresponds to PR #652 on …

Test gen support string additional options 2

---

src/goto-instrument/cover.cpp
src/goto-instrument/cover.h

Cover-function-only limits coverage points to the entry-point function (i.e. the `--function` command-line parameter). It got lost in the repository changes; this reintroduces it based on the patches to `cbmc-testgen`. A subsequent patch uses it in the `test-generator` driver program.

Cover-function-only support

---

src/pointer-analysis/dynamic_object_name.h
src/pointer-analysis/value_set.cpp
src/pointer-analysis/value_set.h
src/pointer-analysis/value_set_fi.cpp
src/pointer-analysis/value_set_fi.h
src/pointer-analysis/value_set_fivr.cpp
src/pointer-analysis/value_set_fivr.h
src/pointer-analysis/value_set_fivrns.cpp
src/pointer-analysis/value_set_fivrns.h

Added usage of dynamic-objects with recency
- replaced the creation of plain dynamic-objects with dynamic-objects flagged with recency at the malloc allocation site.
Propagated changes of dynamic-objects' recency
- applied the changes introduced by the recency property of dynamic-objects.
- added function to get the dynamic-objects' name. Separate function that returns the name of the dynamic-object sent as a read-only parameter. This function is added in a new file, 
`pointer-analysis/dynamic_object_name.h`.

Added usage of dynamic-objects with recency

---

regression/goto-analyzer/approx-array-variable-const-fp/test.desc
regression/goto-analyzer/no-match-dereference-const-pointer-const-array-literal-pointer-const-fp/test.desc
regression/goto-analyzer/no-match-pointer-const-struct-array-literal-non-const-fp/test.desc
regression/goto-instrument/approx-array-variable-const-fp-only-remove-const/test.desc
regression/goto-instrument/approx-array-variable-const-fp-remove-all-fp/test.desc

This prevents spurious test failures on Windows. Fixes #769.

Allow long long int instead of just long int in regexp of some tests

---

src/goto-programs/builtin_functions.cpp
src/java_bytecode/java_bytecode_convert_class.cpp

Not doing this prevented any cast-to-array-type from succeeding, which is common e.g. in return from java.lang.Object.clone.

Initialise array clsid fields

---

src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_entry_point.cpp

Really we should be running them in topographical order (or invoking
them at exactly the time the JVM spec says they will be, even better)
but this is much less effort and works around the common case that
enumeration types are assumed to be initialized by other static init
code, which treats them like global constants.

Run static initializers for enumeration types before all others

---

regression/cbmc-java/enum1/test.desc
src/java_bytecode/java_bytecode_convert_class.cpp

This simply duplicates the contents of an array. Regrettably it uses
a loop to do so at this point because if we use ARRAY_COPY the backend
dies when it can't conclusively establish that the actual parameters have
like type. Some sort of copy-type-from intrinsic would do this, but is
more effort than is sensible to make right now.

Implement Java array.clone

---

src/goto-instrument/cover.cpp

With `--cover-function-only`, all coverage tests should be conditional on
the function containing the target matching `--function`; however this particular
case got missed out.

Coverage (branch mode): add missing is-current-function test

---

.travis.yml

Do not autoupdate Homebrew, and limit cache size to 1G.

Speed up OSX builds on Travis

---

README.md

Added the icon for AppVeyor so we don't miss it when it fails. 
See the README here: https://github.com/thk123/cbmc/tree/feature/appveyor-badge

Adding build icon for AppVeyor

---

src/util/symbol_table.cpp

I spent a while understanding these functions, so I thought I might as well fill in the documentation. I'm a bit unsure for move(), so do check it's correct.
As a side note, I find the convention of returning whether a boolean indicating whether a function failed to be very counter-intuitive, even if it does match the convention of returning 0 if a program succeeded.

Document symbol table functions

---

src/musketeer/fence_inserter.cpp
src/musketeer/fence_inserter.h

musketeer: fix edge types

---

.travis.yml

Do not autoupdate Homebrew, and limit cache size to 1G.
This is a commit cherry-picked from master. See here for more context: https://github.com/diffblue/cbmc/pull/783#issuecomment-292640172

Speed up OSX builds on Travis.

---

src/goto-programs/builtin_functions.cpp

(This is low-priority-- just a cleanup / minor optimisation that had gone astray, which I noticed while preparing https://github.com/diffblue/cbmc/pull/788)
This allows a java-new-array instruction to indicate that the array will be completely initialized immediately afterwards, and therefore the zero-init instruction can be omitted. The nondet object factory currently uses this to note that it will non-det initialize the whole array.

Restore array skip-initialize flag

---

src/goto-programs/remove_instanceof.cpp

This sets the function member for the class identifier assignment when removing instanceof.
fixes diffblue/test-gen#193.

Set function member for class identifier assignment

---

src/cbmc/cbmc_solvers.cpp

We allow setting the options refine-arrays and refine-arithmetic
options in the string solver.
Not setting the refine-arrays option can greatly improve performances.

Allowing some options for string refinement

---

src/goto-programs/builtin_functions.cpp

(This was change appears to have been dropped during the original cbmc/cristina-david/test_gen -> cbmc-testgen move)
Previously all object array allocations became a generic void** when a Java-new operator was lowered into a CPP-new one. Now the type is preserved and is therefore available in the symbol table to build an appropriate source-level type during testcase generation.

Preserve true array type in Java -> GOTO conversion. Fixes #184.

---

src/goto-programs/string_refine_preprocess.cpp

Re-order and categorise the functions in `string_refine_preprocess.cpp`.
This adds clarity.
No functional change.

Order string functions in alphabetical order

---

src/cbmc/Makefile
src/cegis/Makefile
src/pointer-analysis/Makefile
src/pointer-analysis/dynamic_object_name.cpp
src/pointer-analysis/dynamic_object_name.h
src/pointer-analysis/value_set.cpp
src/pointer-analysis/value_set_fi.cpp
src/pointer-analysis/value_set_fivr.cpp
src/pointer-analysis/value_set_fivrns.cpp

- added global string for dynamic-object's prefix
-  used the dynamic-object prefix's global const string
instead of the plain string in VSA.

Replace plain string dynamic-object

---

src/solvers/refinement/string_constraint_generator_valueof.cpp

This fixes diffblue/test-gen#172.
Clarifying number format check and correcting overflow checks.
This solves some issues related to the sign characters in string representing numbers.
The effect of this PR is to reduce the number of test-cases generated for the java `parseInt` function. But the issue is not in this code and is solved by a commit that will be part of another PR.

Fix issue test-gen#172

---

src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_refinement.cpp

Correct bounds in substitute_array_lists.
Add debugging information.
Fix the manual setting of type in if expressions.
Corrections on generated axioms.
Correct axiom on positive length not added to axiom list.
Add missing addition of default axioms in fresh string.
Update documentation.
There is no particular ZenHub issue relating to these fixes.

Various improvements in string refinement

---

src/java_bytecode/java_object_factory.cpp

The pointer code is well suited to handle all types, not just pointers.

Assign variables for all parameters

---

src/goto-programs/interpreter_class.h

Low-priority cleanup.
This is only used in derivative out-of-repo classes, and therefore should be moved there.

Remove trace_stackt

---

src/java_bytecode/java_object_factory.cpp

This was removed because the array is certain to be overwritten with
nondets, and thus the zero-init was worthless-- however, for the special
case of a zero-length array the init statement was the only assignment,
making the difference between the interpreter assigning it value {}
and assigning it no value at all. Ideally we should omit this most of the
time, but its cost is probably minimal and it's much simpler to keep it
than to track down all the special cases required to deal with a symbol
that is referred to but never defined in the inputs map.

Restore array-set for nondet arrays

---

.travis.yml

As a result ccache limit was not applied, and builds were slow.

Travis fix: ccache limit was in the wrong section

---

src/pointer-analysis/value_set_fi.cpp

Replaced `#type` with `ID_C_cxx_alloc_type` in
value_set_fi.cpp.

Used ID_C_cxx_alloc_type in value_set_fi.cpp

---

src/goto-programs/remove_exceptions.cpp

This fixes diffblue/test-gen#215.
The problem was that, whenever the exceptional return was not null, we would incorrectly jump to the end of the function and skip the instruction where the exceptional return value is set.

Always report exception output in __CPROVER_start

---

.travis.yml

This is a counterpart of #816.
As a result of this bug, ccache limit was not applied, and builds were slow.

Travis fix: ccache limit was in the wrong section (test-gen-support version)

---

src/java_bytecode/java_bytecode_convert_method.cpp

This used to assume checkcast required a non-null ref, but actually checkcast (null) always passes. This may increase coverage at constructs like `f((A)null)` which unconditionally cast null, but that's speculative-- I just came across this by chance while testing other things.

Allow checkcast of null pointer

---

src/java_bytecode/java_object_factory.cpp

Previously it was vulnerable to indirect recursion (i.e. A has a B*, B has an A*); this removes that possibility and also simplifies use of the recursion set to only consider pointer edges rather than directly nested struct types, which can't be used to construct an infinite object graph by themselves. This should address some of the cases of prematurely truncated object graphs the incorrect recursion test was trying to solve.
This fixes some cases of infinite recursion seen analysing Tika-batch.

Fix Java object factory recursion set

---

src/ansi-c/padding.cpp

The insert on line 262 invalidates the iterators of the vector which is
being iterated, which may cause the reference on line 206 to dangle.
This in turn leads to undefined behaviour on line 269 when the reference
is passed to a function.
The fix is to take a copy instead of a reference on line 206.

Fix iterator-invalidation bug in ansi-c/padding.cpp

---

src/ansi-c/c_typecheck_type.cpp

If you swap an irep with an irep that it contains, it creates a circular reference which lives until the program quits. Unfortunately, we were doing that in the ansi-c front end, causing the leaks described in #569.

Fix memory leak in ansi-c frontend Fixes: #569

---

CODING_STANDARD
src/analyses/Makefile
src/ansi-c/Makefile
src/assembler/Makefile
src/cbmc/Makefile
src/cegis/Makefile
src/clobber/Makefile
src/cpp/Makefile
src/goto-analyzer/Makefile
src/goto-cc/Makefile
src/goto-diff/Makefile
src/goto-instrument/Makefile
src/goto-programs/Makefile
src/goto-symex/Makefile
src/java_bytecode/Makefile
src/jsil/Makefile
src/json/Makefile
src/langapi/Makefile
src/linking/Makefile
src/memory-models/Makefile
src/miniz/Makefile
src/musketeer/Makefile
src/path-symex/Makefile
src/pointer-analysis/Makefile
src/solvers/Makefile
src/symex/Makefile
src/util/Makefile
src/xmllang/Makefile
unit/Makefile

Now cover how source list of Makefiles should be structured (to aid merging). Also explain the decisions me and Micahel discussed on #454 regarding sharing command flags between programs.

Extended the coding standard

---

regression/cbmc/pointer-function-parameters-2/main.c
regression/cbmc/pointer-function-parameters-2/test.desc
regression/cbmc/pointer-function-parameters/main.c
regression/cbmc/pointer-function-parameters/test.desc
src/ansi-c/Makefile
src/ansi-c/ansi_c_entry_point.cpp
src/ansi-c/c_nondet_symbol_factory.cpp
src/ansi-c/c_nondet_symbol_factory.h
src/java_bytecode/java_entry_point.cpp
src/java_bytecode/java_object_factory.cpp
src/java_bytecode/java_object_factory.h
src/util/std_code.cpp
src/util/std_code.h

Make it match the java code more closely to prepare for (a) one day
merging them and (b) dealing with pointer parameters.

Reorganise C parameter creation

---

src/cbmc/cbmc_parse_options.cpp
src/goto-instrument/cover.cpp
src/goto-instrument/cover.h

I've seen one too many apparent bug attributable to using `--cover` without `--assertions-as-assumptions`. Time to simply make `cover` imply `assertions-as-assumptions`. This PR also moves the coverage option into `goto-instrument/cover.cpp`, which places it better for driver programs that use CBMC to amend and re-use instead of duplicating this code.
Rationale for pushing this upstream: `cover` without `assertions-as-assumptions` is simply incorrect-- code in the wake of an assertion should assume that the assertion passed, and alleged coverage that assumes we magically passed over the assertion while violating its condition is spurious. Open CBMC should either include a coverage mode that works, or not include one at all.

Always convert assertions to assumptions in coverage mode

---

src/cbmc/cbmc_parse_options.cpp

The bmc_cover returns true on error which is translated
into safety_checkert::ERROR in bmc.cpp, which was then
incorrectly translated into exit code 10 instead of 6.
Fixes diffblue/test-gen#201.

Fix translation of safety checker status to exit codes

---

regression/cbmc/unsigned1/main.c
regression/cbmc/unsigned1/test.desc
src/ansi-c/literals/convert_integer_literal.cpp

Only literals with a digit following the initial 0 should be understood as
base-8.

Do not treat integer literals 0u, 0l as base-8

---

src/analyses/goto_check.h
src/cbmc/cbmc_parse_options.cpp

This was CBMC-only. Thus invoking, e.g., goto-instrument would remove all
generated assertions as goto_check replaced them by SKIP.

Configure built-in-assertions for all callers of goto_check

---

src/cegis/cegis-util/type_helper.cpp

The linter has been complaining about `cegis/cegis-util/type_helper.cpp` for a day or so, which stops it finding linting errors elsewhere.
This patch updates the style in this file to bring it in line with the rest of the repo. It also changes a plain loop into `std::any_of` which tidies the code up a bit.

Fix linter complaint

---

src/goto-programs/convert_nondet.cpp
src/goto-programs/replace_java_nondet.cpp

This patch implements a fix for #850. I haven't added a regression test, because such a test would require that `org.cprover.jar` had already been built and placed in a known location.
Erasing a range of instructions from a goto program can cause memory bugs when `goto_program::update` is called. Specifically, if any of the remaining nodes in the program have elements of `targets` which point into the erased range, then the program may attempt an invalid read during the `update` call.
To avoid this, I thought of two options:
- check through the goto-program for instructions with `target`s that point into the removed range, and remove those `target`s, or
- just replace the existing instructions with no-ops.
Although I think the first solution is better, I can't think of a good way of doing …

Remove 'erase' in replace_java_nondet.cpp, fixes #850

---

pkg/arch/PKGBUILD
pkg/arch/README.md

Arch Linux use `PKGBUILD` file to create package. One can use `PKGBUILD` file from this commit (see README.md)
This was requested by @kroening and moved/updated here at the request of @peterschrammel.

Add CBMC package build file for Arch Linux

---

COMPILING
src/util/unicode.cpp
src/util/unicode.h
unit/Makefile
unit/unicode.cpp

* Remove an unused utf16 to utf8 conversion function that is broken anyway, and tidy utf32 to utf8.
* Change utf8 to utf16 conversion to not require codecvt.
This should make the PR #752 unnecessary.

Unicode support cleanup

---

src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_parser.cpp

`membert` has Booleans `is_public`, `is_private` and `is_protected`. This was used, but not set in `fieldt` and set but not used in `methodt`.
This also adds `ID_default` when no other flag is set, in Java this allows visibility in the package, but not subclasses outside the package (cf. https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html)

add visibility information for fields and methods

---

src/util/irep_ids.def
src/util/irep_ids.h

I think it's best to have the docs for this in the same file, rather than on the wiki, so that they get incorporated properly when we move to Doxygen.

Add documentation to irep_ids

---

src/goto-instrument/cover.cpp

This unifies test-generator's version of coverage instrumentation with cbmc's base version, which should make future changes to the two easier to keep in sync.
An upcoming changeset will update the test-generator tool to use this.

Move coverage arg-parsing into cover.cpp

---

src/util/ssa_expr.h

This patch fixes an issue where `ssa_exprt::get_object_name` returns a const reference to an object with stack-bound lifetime.

Fix return of temporary ref in ssa_exprt

---

src/analyses/ai.cpp
src/analyses/flow_insensitive_analysis.cpp
src/analyses/static_analysis.cpp
src/cegis/cegis-util/program_helper.cpp
src/goto-instrument/accelerate/all_paths_enumerator.cpp
src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
src/goto-instrument/accelerate/sat_path_enumerator.cpp
src/goto-instrument/accelerate/trace_automaton.cpp
src/goto-instrument/call_sequences.cpp
src/goto-instrument/dot.cpp
src/goto-instrument/wmm/goto2graph.cpp
src/goto-programs/goto_program_template.h
src/goto-programs/remove_unreachable.cpp

The biggest change is to `goto_program_templatet::get_successors`, which now returns a list of targets instead of modifying a list which was passed-by-reference. With move semantics, there should be no performance penalty. It also cleans up call sites of this method, which no longer need to have a preceding list declaration.
This change was made because there were two version of `get_successors`, one `const` and one not, with slightly different implementations. By templating the method on the `Target` type, we can reduce duplication, and avoid bugs where const- and non-const-methods have different behaviours.
Also replaced a few iterator increments/decrements with `std::next` and `std::prev`, and made some const-correctness fixes.

Improve style in goto_program_template.h

---

src/java_bytecode/expr2java.h

Instead of declaring new methods which call the methods in the base
class, use 'using expr2ct::convert;'.

Clean up code

---

src/goto-programs/goto_inline.cpp

Added comments
Moved check for _start function out of instruction loop
Pass adjust_function parameter to sub-call (it was previously ignored)

Fixed inefficiency and failure to pass on parameter

---

src/util/tempfile.h

Implicit copy constructor leads to double deletion of files. Added explicit move
constructor to allow returning temp_filet.

Deleted copy/added explicit move constructor.

---

appveyor.yml
src/config.inc
src/util/unicode.cpp

Also enabled warnings as errors in config.inc to match travis settings

Fixed warning in unicode.cpp causing build failure

---

src/util/irep_hash_container.cpp
src/util/irep_hash_container.h

This breaks the need to have irep_hash.h included in the irep hash container header file, which then propagates it elsewhere. This is important as irep_hash.h defines a macro that clashes with Boost.

Moved vector_hasht implementation into cpp file

---

src/solvers/refinement/string_refinement.cpp
src/solvers/refinement/string_refinement.h

This rewrites part of the concretization process of strings. We now re-use the last concretized value, which avoids extra calls to the solver and also avoids over-constraining the model with lemmas, which resulted in missing test cases.
The related issue is here : diffblue/test-gen#158

Fix issue #158 (missing test cases)

---

regression/cbmc-cover/built-ins1/main.c
regression/cbmc-cover/built-ins1/test.desc
regression/cbmc-cover/built-ins2/main.c
regression/cbmc-cover/built-ins2/test.desc
regression/cbmc-cover/built-ins3/main.c
regression/cbmc-cover/built-ins3/test.desc
regression/cbmc-cover/built-ins4/main.c
regression/cbmc-cover/built-ins4/test.desc
regression/cbmc-cover/built-ins5/main.c
regression/cbmc-cover/built-ins5/test.desc
regression/cbmc-cover/built-ins6/main.c
regression/cbmc-cover/built-ins6/test.desc
regression/cbmc-cover/built-ins7/main.c
regression/cbmc-cover/built-ins7/test.desc
src/goto-instrument/cover.cpp

fixes https://github.com/diffblue/cbmc/issues/259

Do not instrument built-ins

---

src/solvers/refinement/string_refinement.cpp

Avoid initialising the index set if not needed. This can improve performances when strings are not important.
Addresses diffblue/test-gen#199.
Depends on PR #819 (will have to be rebased once #819 is merged).

Improve performance by avoiding init of index set

---

src/solvers/refinement/string_refinement.cpp

Adding namespace to arguments of from_expr in debug
Not finding a symbol in from_expr can cause some exception to be thrown.
This was happening while outputing debug information in some examples
when --refine-strings was activated.

Fix issue cbmc/test-gen#201

---

src/ansi-c/expr2c.cpp
src/ansi-c/expr2c_class.h
src/cpp/expr2cpp.cpp
src/java_bytecode/expr2java.cpp
src/java_bytecode/expr2java.h

It is bad style to have an interface method the same name as an
internal method with a different signature. Then on overriding one of
these methods the compiler only finds the overloaded one with the wrong
signature, doesn't look up the base class and fails.
We fix this problem by renaming the protected method. This simplifies
the code in all derived classes.
This is an improvement on #888 , as suggested by @peterschrammel .

Rename convert to convert_with_precedence

---

.travis.yml
CODING_STANDARD
appveyor.yml
unit/.gitignore
unit/Makefile
unit/catch.hpp
unit/catch_entry_point.cpp
unit/catch_example.cpp
unit/unit_tests.cpp

Adds catch.hpp - a test harness for writing and running unit tests. Updated the make file so that running `make test` runs all the tests. I removed all the tests that either didn't compile, failing on running or
didn't terminate without some input.
Added an example catch test to demonstrate it working.
Updated one of the unit tests to use catch as a demonstration (I can do the others in the next sprint if it is deemed important).

Add the Catch unit testing framework

---

src/goto-instrument/wmm/goto2graph.cpp
src/goto-programs/goto_functions.h
src/goto-programs/goto_functions_template.h
src/goto-programs/goto_model.h
src/goto-programs/goto_program.h
src/goto-programs/goto_program_template.h

Previously `goto_modelt` implemented a non-standard move constructor and didn't enable the assignment operator. This replaces that code with the standard way of achieving the desired result.
This also removes the copy constructor from `goto_functions_templatet` rather than just telling people not to use it.

Enable goto_modelt move assignment

---

src/goto-programs/remove_exceptions.cpp

This should fix~ diffblue/test-gen#276

Always initialise the exceptional return variable of the entry function

---

CODING_STANDARD

I gather that this language feature is allowed, but it isn't used.
Perhaps if it's clearer that it's allowed in the coding standard
then people will realise they can use it.

Allow anonymous namespaces

---

src/util/tempfile.cpp
src/util/tempfile.h

Replaced move constructor by "swap" on default-constructed, empty
string. This because the std::string move constructor does not guarantee
that the moved string is actually erased. Also added test so we don't
unnecessarily call "unlink" on an empty string, even though this has no
effect.

Avoid unlink call on empty string

---

unit/Makefile

This Makefile overrides LIB rather than adding to it.
This causes issues in environments where LIB is already set. Currently this is only MSVC for the SSS branch.

Fix missing += in Makefile that causes issues in building unit test

---

src/cbmc/bmc.h

There are two versions of bmc_cover (one in the private, one in the public repo). This new class will minimize duplicate code by using a templated version instead.
I used a new class name so that we don't need to synch pull requests as this is needed by pull request 
diffblue/test-gen#320.

Added new friend to bmc to handle refactoring

---

.travis.yml
unit/miniBDD.cpp

There is an ambiguity in this expression caused by a mix of bit-wise (operator&) and logical (operator!) operators in mini_bdd.
Personally I would change the bit-wise operators to logical operators in mini_bdd but some concern was raised that people may then wrongly expect them to short-circuit, as the Boolean logical operators do. (Overridden logical operators do not short-circuit, as stated here under *Restrictions*: http://en.cppreference.com/w/cpp/language/operators.)
The other option would be to change the operator! to operator~, but in my opinion this would be moving in the wrong direction and reduce code-clarity.

Add brackets to resolve ambiguity

---

src/goto-programs/string_refine_preprocess.cpp

Fixes the use-after-free bug seen in diffblue/test-gen#268. I know this will also be fixed by diffblue/test-gen#130, but I'd quite like a non-buggy build to test against in the meantime.
The technique is to take copies rather than references in a few places. Before, these references pointed into containers which were modified, invalidating the references.

Fix use-after-free bugs in string refinement

---

src/cpp/expr2cpp.cpp
src/jsil/expr2jsil.cpp

Now that PR #916 has been merged, we don't need to manually forward
convert(const exprt) and convert(const typet) calls to the base class.

Remove unneeded code

---

src/java_bytecode/java_entry_point.cpp
src/java_bytecode/java_object_factory.cpp
src/java_bytecode/java_object_factory.h

This factors the Java object factory to:
(a) improve input declarations
(b) Refactor for clarity (replace some explicit gotos with higher-level code-ifthenelse constructs, by @owen-jones-diffblue)
(c) Split out certain parts of the nondet-init logic into individual functions, to make the diff vs. test-gen-support's version of the same code friendlier and make them more merge-compatible.
Depends on https://github.com/diffblue/cbmc/pull/823

Refactor java object factory

---

src/util/irep.h
src/util/merge_irep.h

This PR fixes up the behaviour of `SHARING` so that it can be disabled if necessary. I think the way that `SHARING` is currently used could be improved - see for details. #907

Fix SHARING behaviour

---

src/analyses/local_bitvector_analysis.cpp

When running the [linked program](https://github.com/diffblue/cbmc/files/928455/id.000118.sig.04.src.000006.op.arith8.pos.5884.val.-3.zip)
(thanks @mgudemann for the test case) with cbmc under address-sanitizer, we get the following error:
```
Reading GOTO program from file
Reading: /home/reuben/Downloads/more crashes/crashes/id:000118,sig:04,src:000006,op:arith8,pos:5884,val:-3
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Partial Inlining
Generic Property Instrumentation
=================================================================
==6360==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000009b70 at pc 0x000001004d5d bp 0x7ffceb271700 sp 0x7ffceb2716f8
READ of size 8 at 0x603000009b70 thread T0
#0 0x1004d5c …
```

Add assert to local_bitvector_analysis.cpp

---

src/java_bytecode/Makefile
src/java_bytecode/character_refine_preprocess.cpp
src/java_bytecode/character_refine_preprocess.h
src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_class.h
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_convert_method.h
src/java_bytecode/java_bytecode_convert_method_class.h
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_bytecode_language.h

This preprocessing is meant to replace simple methods of the Character
Java in goto-programs by expressions on characters.
About 60% of the library is supported, but for some of this
methods are limited to ASCII characters.
This is meant to be run in conjunction with the string refinement so
it is called if the string-refine option is activated.
Note that the string-refine option is added in PR #429, but this PR can be merged independently.

Adding preprocessing for functions of the Java Character library

---

regression/Makefile
regression/goto-analyzer/constant_propagation_10/constant_propagation_10.c
src/analyses/dependence_graph.cpp
src/analyses/dependence_graph.h
src/analyses/interval_domain.cpp
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-programs/remove_unreachable.cpp
src/goto-programs/remove_unreachable.h

Low risk changes needed for the goto-analyze branch. Mostly additions.
Note that this has been reviewed as part of https://github.com/diffblue/cbmc/pull/472 .

Goto analyzer 5 part1

---

COMPILING
src/jsil/Makefile

Fix coverage build

---

src/analyses/ai.cpp
src/analyses/ai.h
src/analyses/constant_propagator.cpp
src/analyses/constant_propagator.h
src/analyses/interval_domain.cpp
src/analyses/interval_domain.h
src/goto-programs/remove_unreachable.cpp
src/util/replace_symbol.h

Low risk changes needed for the goto-analyze branch. Mostly additions.
Note that an earlier version of this has been reviewed as part of #472, there have been some changes.

Goto analyzer 5 part2

---

src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_parse_options.h
src/solvers/flattening/bv_pointers.cpp

get_goto_program may affect configt, in particular the ansi_c.pointer_width.
Thus prop_convt may be configured with the wrong pointer width in bv_pointerst.
It is not clear from the code base what get_modules is meant to do.

Do not configure bmct/prop_convt before reading goto programs

---

src/ansi-c/ansi_c_convert_type.cpp
src/ansi-c/c_typecheck_type.cpp
src/util/c_types.cpp
src/util/c_types.h

An attempt is made to make the functions in c_types.h return the strongest possible C++ type

Make the c_types have stronger C++ types

---

src/util/std_types.h

To avoid usage of `get` directly, introducing accessors  for the access properties of functions.  Required as part of diffblue/test-gen#393

Adding accessors for the access properties

---

regression/cbmc/byte_update8/main.c
regression/cbmc/byte_update8/test.desc
regression/cbmc/byte_update9/main.c
regression/cbmc/byte_update9/test.desc
regression/cbmc/little-endian-array1/main.c
regression/cbmc/little-endian-array1/test.desc
regression/cbmc/memset1/main.c
regression/cbmc/memset1/test.desc
src/ansi-c/ansi_c_internal_additions.cpp
src/ansi-c/c_typecheck_expr.cpp
src/ansi-c/expr2c.cpp
src/ansi-c/expr2c_class.h
src/ansi-c/library/cprover.h
src/ansi-c/library/stdlib.c
src/ansi-c/library/string.c
src/ansi-c/library/unistd.c
src/goto-programs/builtin_functions.cpp
src/goto-programs/goto_convert_class.h
src/goto-programs/string_abstraction.cpp
src/goto-symex/symex_clean_expr.cpp
src/goto-symex/symex_other.cpp
src/pointer-analysis/value_set.cpp
src/pointer-analysis/value_set_dereference.cpp
src/pointer-analysis/value_set_fi.cpp
src/solvers/flattening/flatten_byte_operators.cpp
src/util/irep_ids.def
src/util/pointer_offset_size.cpp
src/util/simplify_expr.cpp
src/util/simplify_expr_pointer.cpp
src/util/std_expr.h

This avoids byte-wise copy loops in several places.

Implement C library string functions via array_{copy,replace,set}

---

regression/cbmc-java/virtual7/test.desc
src/analyses/Makefile
src/analyses/uncaught_exceptions_analysis.cpp
src/analyses/uncaught_exceptions_analysis.h
src/goto-programs/remove_exceptions.cpp

This analysis computes for each function an overapproximation of the set of exceptions that escape it and it is used to reduce the number of exceptional return variables introduced by the exception handling. Consequently, using this analysis reduces the amount of dead code introduced by the exceptions instrumentation and described in diffblue/test-gen#319
This used to be PR #510 on cbmc/master and is now moved to test-gen-support, as requested by @jgwilson42.

Uncaught exceptions analysis

---

src/goto-symex/symex_goto.cpp

Each iteration of the loop yields the same expression. Avoiding repeated
construction enables trivial sharing rather than relying on merge_irepst for
a reduced memory footprint, and reduces the computational cost as
guardt::operator-= is non-trivial.
This is one of the patches from #363.

Avoid repeated computation of guardt::operator-=

---

src/java_bytecode/character_refine_preprocess.cpp

The wrong function was previously called: `expr_of_is_unicode_identifer_part` instead of `expr_of_is_unicode_indentifier_start`.
This is related to diffblue/test-gen#118

Fix a mistake in convert_is_java_identifier_start

---

src/java_bytecode/java_object_factory.cpp

We assume the array field of Strings to be non-null.
This is related to issues diffblue/test-gen#240 , https://github.com/diffblue/test-gen/issues/328 and PR diffblue/test-gen#317

Disallow null pointer in data field of String

---

src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_testing.cpp

We now have a special way of dealing with "contains" in the case the argument is a constant, which seems to be much more efficient.
This relates to issue: diffblue/test-gen#159

Specification for contains in the case of a constant argument

---

src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_class.h
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_convert_method.h
src/java_bytecode/java_bytecode_convert_method_class.h
src/java_bytecode/java_string_library_preprocess.h

Only one instance of this class should exist for a program.
We forbid copies by making it private.
This corrects potential issues with PR https://github.com/diffblue/cbmc/pull/906

Forbid copies of string preprocess

---

src/solvers/refinement/string_refinement.cpp

There was a mistake that could cause looping over symbols in the map that don't actually need to be modified and could greatly slow down the analysis.

Correcting addition of symbol to symbol map

---

src/goto-programs/json_goto_trace.cpp
src/util/json_expr.cpp
src/util/json_expr.h

The c_type field is confusing if the original program is in Java since the types do not match.
This adds a `java_type` field in the json output which clarifies what the type should be for Java.
This is in response to the issue raised here: diffblue/test-gen#294

Adding java_type field in json for bit vector values

---

src/java_bytecode/java_string_library_preprocess.cpp
src/java_bytecode/java_string_library_preprocess.h

We now assign strings in one step instead of field by field.
This makes constant propagation work better in later step of the analysis.
This is necessary for the implementation of String.replace().
Part of diffblue/cbmc#256.
Partly replaces #984.

Improve constructor and copy of strings

---

src/java_bytecode/java_string_library_preprocess.cpp

In add_string_type, instead of removing the symbol from the symbol
table and then adding one with the same name, we use symbol.move to
get a pointer to the existing symbol if it exist or create a new one.
This should prevent the memory issues mentionned in diffblue/test-gen#480

When adding String type, take care of cases where the symbol exists in table

---

src/util/json_expr.cpp

This prevents memory leaks when using json output.

Delete language pointer created by get_language_from_mode

---

src/java_bytecode/java_string_library_preprocess.cpp
src/java_bytecode/java_string_library_preprocess.h
src/solvers/refinement/string_constraint_generator_constants.cpp

This provides code for `Object.getClass` during bytecode conversion.
This is done by a call to `Class.forName`, so it will only work well when a model for this method is available.
This is part of issue diffblue/test-gen#272 ~and depends on pull request https://github.com/diffblue/cbmc/pull/906~ (merged)

Code for Object.getClass in bytecode conversion

---

src/cbmc/bmc.cpp

Traces can't be caught with a messaget; this fixes that so they are printed like everything else.

Write traces to status() not cout

---

src/solvers/prop/prop.h
src/solvers/prop/prop_conv.h
src/solvers/sat/satcheck_minisat2.cpp
src/solvers/sat/satcheck_minisat2.h

Currently only minisat2 supports this. This allows us to kill minisat after a specified time limit (in seconds). Used by object synthesis, to bound the time spent searching for a constructor / mutator sequence.

Add simple time limiting to prop_conv and propt

---

src/analyses/interval_domain.h
src/analyses/interval_template.h
src/analyses/invariant_set.h

It's now called interval_templatet, I believe this is desired behaviour.

Added a 't' to the name of interval_template 

---

scripts/ls_parse.py

Add ls_parse.py, a script to discover symbols whose values are defined
in a linker script, and valid memory extents corresponding to sections
in an object file. ls_parse can emit this information as a C file,
suitable for compiling into a goto-binary and linking with the rest of
the codebase. ls_parse can also emit the information as a JSON file,
suitable for automatic processing from within goto-cc. This supports
CPROVER in knowing the actual values of symbols that are not defined in
the C source.

Add script to find linkerscript-defined info

---

scripts/reformat_docs.py

Updates the documentation conversion script so that it doesn't try to convert file headers which have already been converted. This should mean that, after the initial run, subsequent runs of the `do_doc_convert` script do not make any changes to the codebase, which should make rebases from pre-Doxygen code much easier.

Stop attempting to convert previously-converted doc headers

---

regression/goto-instrument/print-internal-representation/main.c
regression/goto-instrument/print-internal-representation/test.desc
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h

This flag pretty-prints every instruction in the entire program. I use
it to learn about CPROVER's internal representation of particular
constructs, by passing in --print-internal-representation on a one-line
C program.

Add --print-internal-representation to goto-instrument

---

src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_parse_tree.cpp
src/java_bytecode/java_bytecode_parse_tree.h
src/java_bytecode/java_bytecode_parser.cpp
src/java_bytecode/java_types.h

These are Java public, protected and private class flags, in similar style to the existing field flags.

Add support for recording and propagating class access flags

---

src/ansi-c/ansi_c_internal_additions.cpp
src/ansi-c/library/cprover.h
src/ansi-c/library/math.c
src/goto-programs/builtin_functions.cpp

The collection of patches from #363 (with some squashes) mostly provided by Martin.

Float-point library implementation

---

src/java_bytecode/bytecode_info.cpp

(Source: https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html)
Nothing appears to use the annotation at the moment, so it cause any ill behaviour and can't be tested, but in case it becomes used in the future we might as well correct it.
Also corrected the Wikipedia page where the mistake originated ;)

Fix sipush return type annotation

---

src/pointer-analysis/value_set_fivr.h
src/pointer-analysis/value_set_fivrns.cpp
src/pointer-analysis/value_set_fivrns.h
src/solvers/sat/satcheck_minisat2.cpp

Do the appropriate changes to make PR #1032 work

Add empty() to containers with size()

---

src/goto-programs/interpreter.cpp
src/goto-programs/interpreter_evaluate.cpp

"Infinite size arrays not supported" and "Failed to concretize variable
array" are now warnings rather than errors.

Change two errors to warnings

---

src/solvers/prop/prop.h
src/solvers/sat/satcheck_minisat2.cpp

Stubbed out signal handler usage in the Win32 case and added stdint include.

Fix test-gen-support win32 compilation

---

regression/strings-smoke-tests/java_replace/test.desc
src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_concat.cpp

Add an `add_axioms_for_concat_substr` function in string constraint generation.
Implements the concatenation of a substring of the second argument.
This will make the encoding of `StringBuilder.append(CharSequence s, int start, int end)` more efficient.
Part of diffblue/test-gen#256.
No direct dependency.

Add add_axioms_for_concat_substr

---

src/java_bytecode/java_string_library_preprocess.cpp
src/solvers/refinement/string_constraint_generator_transformation.cpp

This fix a wrong statement in the substring primitive of the solver and some missing declaration of string symbols in the preprocessin.

Fix small bugs in string support related to Object.getClass

---

src/solvers/refinement/string_refinement.cpp

Otherwise it can't find symbol identifiers and can crash when trying to e.g. pretty-print structure names.

Always pass namespace to from_expr

---

src/java_bytecode/java_string_library_preprocess.cpp
src/java_bytecode/java_string_library_preprocess.h

Remove:
- StringBuilder.append(Object)
- StringBuilder.append(Float)
- StringBuilder.append(Int)
- StringBuilder.append(Long)
This functions should have java models for them provided instead of
having special treatments for them in the solver.
To be easier to maintain, the solver should only make atomic
operations available, such as concatenation of two strings and
conversion from primitive types to string.
This prevents crashes as mentioned in https://github.com/diffblue/test-gen/issues/442

Remove functions that are destined to be modelled in Java

---

src/cbmc/bmc.cpp
src/util/cout_message.cpp
src/util/cout_message.h
src/util/message.cpp
src/util/message.h
src/util/ui_message.cpp
src/util/ui_message.h

This allows users of a message handler to note they have already formatted a particular message according to its output conventions (currently XML or JSON) and so output something more complicated than it can synthesise on its own.
Addresses @peterschrammel objection to https://github.com/diffblue/cbmc/pull/1003#pullrequestreview-46074082 (and uses that particular output site as a proof of concept).

Add preformatted message flag

---

src/goto-instrument/cover.cpp
src/goto-instrument/cover.h

check whether the java bytecode index matches for the existing coverage goals.

check for java bytecode index in the existing coverage

---

regression/cbmc/bad_option/main.c
regression/cbmc/bad_option/test.desc
regression/cbmc/bad_option/test_multiple.desc
src/util/cmdline.cpp
src/util/cmdline.h
src/util/parse_options.cpp
src/util/parse_options.h

During command line parsing, if an unknown option is read, store it and output an error message at `parse_options_baset::main`.
This adds a message when the command line parser finds an unknown option. Ideally, this should be done using the `messaget` framework, but `parse_options_baset` does not inherit from it. All messages produced in this context are directly sent to the standard (as for the help string) or the error outputs.
This should also be applied to cbmc/master.

Add message for unknown cbmc option

---

src/goto-programs/class_hierarchy.cpp
src/java_bytecode/java_object_factory.cpp

As part of diffblue/test-gen#402 I split up `get_nodet_init` so this PR just does this to split up the changes (and so I can get this in sooner)

Refactor gen_nondet_init

---

src/goto-programs/class_hierarchy.cpp
src/java_bytecode/java_object_factory.cpp

I split up get_nodet_init so this PR just does this to split up the changes (and so I can get this in sooner).
This PR is already targeted to test-gen-support (#990), but to ease merging, here is a version for master.

Refactor gen_nondet_init to master

---

src/goto-programs/mm_io.cpp

E.g. the full slicer relies on function being set and will abort
with an assertion violation in that case.

Assign function in instructions introduced by MM I/O instrumentation

---

scripts/cpplint.py

Removal of first component for header guard suggestion is hard-coded to
remove 4 characters ("src/").  This doesn't work with all directory
names ("unit/").

Fix removal of first component

---

CHANGELOG
regression/goto-instrument/dump-vararg1/main.c
regression/goto-instrument/dump-vararg1/test.desc
regression/goto-instrument/typedef1/main.c
regression/goto-instrument/typedef1/test.desc
regression/goto-instrument/typedef2/main.c
regression/goto-instrument/typedef2/test.desc
regression/goto-instrument/typedef3/main.c
regression/goto-instrument/typedef3/test.desc
regression/goto-instrument/typedef4/main.c
regression/goto-instrument/typedef4/test.desc
src/ansi-c/expr2c.cpp
src/clobber/clobber_parse_options.cpp
src/goto-cc/compile.cpp
src/goto-instrument/dump_c.cpp
src/goto-instrument/dump_c.h
src/goto-instrument/dump_c_class.h
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-instrument/goto_program2code.cpp
src/goto-instrument/goto_program2code.h
src/goto-programs/read_goto_binary.cpp
src/util/find_symbols.cpp

Follow-up to 99067de178170a, which made expr2c prefer typedef names over
original type expressions.

Fix dump-c output involving typedef names

---

src/java_bytecode/java_entry_point.cpp
src/java_bytecode/java_entry_point.h

Fixes https://github.com/diffblue/platform/issues/1006

Fix modes in java entry point code

---

regression/cbmc/pointer-function-parameters-2/test.desc
regression/cbmc/pointer-function-parameters/test.desc
src/goto-symex/build_goto_trace.cpp

When building the goto trace we remove the SSA ids from most variable
names, but they were still in address-of expressions in the right hand
sides of assignments.

Remove SSA ids from goto trace

---

regression/cbmc/unwind_counters1/main.c
regression/cbmc/unwind_counters1/test.desc
regression/cbmc/unwind_counters2/main.c
regression/cbmc/unwind_counters2/test.desc
regression/cbmc/unwind_counters3/main.c
regression/cbmc/unwind_counters3/test.desc
src/goto-symex/goto_symex.h
src/goto-symex/symex_function_call.cpp
src/goto-symex/symex_goto.cpp
src/goto-symex/symex_main.cpp

Constant propagation and simplification may determine that a loop cannot be
unrolled further. This is determined at the loop head, which is a forward goto
in case of for or while (but not do-while) loops. Before this patch, forward
gotos would never cause loop counters to be reset. In nested loops, the inner
loop(s) would thus have their unwinding counts added to previous (complete) loop
executions.

Reset unwinding counters when leaving a loop at the loop head

---

src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_instrument.cpp
src/java_bytecode/java_utils.cpp
src/java_bytecode/java_utils.h

I found a few cases where goals were going missing when instrumentation was introduced, which appeared to be due to GOTO targets (`code_labelt`s) losing their source locations when they got instrumented. This ensures that replaced code inherits a source location, and more generally that source locations are assigned to and retained by GOTO instructions.

Ensure source locations are kept across code instrumentation

---

src/solvers/refinement/string_constraint_generator_valueof.cpp

Type for value comparison with zero was wrong, causing warning about
ignoring comparison.

Correcting type in add axiom for int

---

src/cbmc/cbmc_parse_options.cpp
src/clobber/clobber_parse_options.cpp
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_class_loader_limit.cpp
src/util/language.h

`--show-parse-tree` did not call `get_language_options`, therefore required parameters were not set in the Java front-end, for example the class file loader regexp.

Call `get_language_options` on `--show-parse-tree`

---

regression/cbmc/Local_out_of_scope3/main.c
regression/cbmc/Local_out_of_scope3/test.desc
src/goto-symex/symex_assign.cpp

Pointer dereferencing may yield objects that have meanwhile gone out of scope.
As an optimisation, assigning to them is unnecessary. It is, however, essential
not to perform a merge when only one of the states entering the phi node
actually has an (L1) object. The optimisation guarantees that the latter does
not happen.
Fixes: #1115

Do not assign to objects that have gone out of scope

---

src/cbmc/cbmc_parse_options.cpp
src/goto-programs/remove_static_init_loops.cpp
src/goto-programs/remove_static_init_loops.h

This checks whether a function symbol is in the symbol table before it tries to
remove loops from the static initializer.
Fixes the issue at hand, but it is not clear where the offending goto-function is coming from.

Skip functions not in the symbol table in remove <clinit> loops

---

src/goto-cc/as_cmdline.cpp
src/goto-cc/as_mode.cpp
src/goto-cc/gcc_mode.cpp

Make sure exit codes and version output match GCC's when operating in goto-gcc mode. In goto-as mode, handle input from stdin.

Improve goto-gcc/-as compatibility with GCC

---

src/goto-cc/gcc_mode.cpp

goto-gcc now selects the correct architecture when x86_64, power, or
HP-PA specific flags are passed to -mtune, -march or -mcpu.

[goto-gcc] Add arch flags for x86_64, power, hppa

---

src/util/threeval.h

Despite it being safe to mark it as such.  All other similar methods being marked as const.  This commit marks the method as const.

tvt's || operator is not marked as const

---

src/goto-cc/gcc_mode.cpp

goto-cc calls objcopy with a native prefix if GCC is being used to link
several object files, and the name of the compiler begins with some
native prefix (like arm-none-eabi-gcc).
Previously, goto-cc would only prepend a native prefix to objcopy if the
linker command had a native prefix. This commit causes goto-cc to work
on codebases that use GCC rather than LD to link, and that use a
cross-compiler with a native-prefixed name.

Use native objcopy when linking with GCC

---

src/goto-symex/goto_symex_state.cpp

The previous code was a non-trivial expression always returning true.
Fixes: #351

Do not constant propagate multiplication unconditionally

---

src/util/graph.h

This adds topological sorting to `graph.h`.

Add Kahn's algorithm to graph.h

---

src/goto-programs/convert_nondet.cpp
src/java_bytecode/java_object_factory.cpp
src/java_bytecode/java_object_factory.h

Previously, since the `update_in_place parameter` is optional and there is one too few parameters, the `NO_UPDATE_IN_PLACE` was being interpreted as the `max_nondet_array_length` (i.e. of 0) and the `max_nondet_array_length` was being used as the assume_not_null (presumably true) and `!nullable`
was being used as `create_dyn_objects`.
I took a guess it should be `true` - but this should be verified! 
I removed the default parameter as it wasn't even being used anywhere, except erroneously. 
test-gen PR: diffblue/test-gen#766

Added in parameter to correct call to gen_nondet_init

---

regression/goto-analyzer/precise-const-fp-supurious-const-loss/main.c
regression/goto-analyzer/precise-const-fp-supurious-const-loss/test.desc
src/analyses/does_remove_const.cpp
src/analyses/does_remove_const.h
unit/Makefile
unit/analyses/does_remove_const/does_expr_lose_const.cpp
unit/analyses/does_remove_const/does_remove_const_util.h
unit/analyses/does_remove_const/does_type_preserve_const_correctness.cpp
unit/analyses/does_remove_const/is_type_at_least_as_const_as.cpp

There is a bug in `does_remove_const` analysis where code like this:
```C
const int a = 4;
int b = a;
```
Would cause it to think the const-correctness had been lost (as detailed in diffblue/cbmc-toyota#127 :lock:)
This fixes this by applying a more subtle condition when checking whether an assign statement actually violates const correctness:
```
if the type is a pointer:
then the target subtype should be at least as const as the source subtype.
also if the subtype is a pointer then this check should be recursively applied on this subtype
if the type is not a pointer we no longer require it to be at least as const
```
Added unit tests to document exactly what the two methods do as the difference is quite subtle. The unit tests are a little difficult to read (and I'd ideally like to test …

Fix irrelevant loss of const throwing off the const analysis

---

src/java_bytecode/java_bytecode_convert_method.cpp

In `java_bytecode_convert_methodt::convert_instructions` (specifically the branch for "getstatic"), the special case of `$assertionsDisabled` was handled incorrectly when `--lazy-methods` is enabled. The class associated with `$assertionsDisabled` was not registerd with lazy methods. This is now fixed.
This is related to diffblue/test-gen/issues/747.

Added `$assertionsDisabled` case in `java_bytecode_convert_methodt::convert_instructions` ("getstatic" branch).

---

regression/failed-tests-printer.pl
regression/test.pl

Solves the following issue: https://github.com/diffblue/test-gen/issues/680
Changes test.pl to name output *.out files after *.desc instead
of *.class files. Also updates failed-test-printer.pl to work with
those new *.out files.

Adapt perl script to handle multiple .desc files

---

src/util/symbol.h
unit/Makefile
unit/src/ansi-c/c_to_expr.cpp
unit/src/ansi-c/c_to_expr.h
unit/src/expr/require_expr.cpp
unit/src/expr/require_expr.h
unit/unit_tests.cpp

I developed some utilities and fixed the Makefile for the `unit` directory. Rather than wait for that work to make its way to master, here are those improvements as they may be useful to others. 
Would like some feedback on the directory structure - I wanted to keep utility code separate from the unit tests themselves. If people agree, I can add this to the coding standard.

Improvements to the unit tests directory

---

src/solvers/flattening/arrays.cpp
src/solvers/flattening/arrays.h

* Use ranged for
* Use full index_exprt constructors
* Cleaned out unused method prototype

cleanup array theory solver

---

src/goto-programs/interpreter_class.h

This could previously overestimate object sizes, potentially by including
all other objects in the address space in the size estimate. That could
lead to overly long variable-length arrays, with performance cost though
most likely no correctness problems in Java, since all arrays have an
explicit length.

Fix interpreter allocation sizing

---

src/solvers/refinement/string_refinement.cpp

The function changed (`string_refinementt::instantiate`) is used to instantiate the universal constraint `axiom` with an element `val` of the index set of `str`. To do this it must find an occurrence of `axiom.univ_var()` in an index expression on `str`. However, `find_index` only found *an* index expression involving `str`. Hence, looking for `axiom.univ_var()` in just one index expression was incorrect, we care about there being at least one, not all. Now `find_index` only returns an index with the given `qvar`.
Also fixed some whitespace errors and switched a loop for clarity.
The related issue is diffblue/test-gen/issues/780.

Corrected instantiation of universal string constraints.

---

src/goto-symex/build_goto_trace.cpp
src/goto-symex/symex_target.h
src/goto-symex/symex_target_equation.cpp
src/goto-symex/symex_target_equation.h

Same as #864, but targeting master.

Assignment typet fix master

---

src/analyses/ai.cpp
unit/Makefile
unit/analyses/ai/ai_simplify_lhs.cpp

The `simplify_lhs` had the boolean flag the wrong way round.

Fixing simplification of LHS 

---

src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_refinement.cpp

The previous implementation was adding string constraint directly on the arrays, which does not work very well because the length is not controlled at that point.
We now generate this constraints when a string is constructed from these arrays.
In addition we propagate the index set of if expressions to the arrays contained in the branches.

Improve the handling of if expressions representing character arrays

---

src/java_bytecode/java_string_library_preprocess.cpp

This method was missing and is useful is some cases.

Handle String.toString() in preprocess

---

src/solvers/refinement/string_refinement.cpp
src/solvers/refinement/string_refinement.h

This improves the displaying of the model on the debug output by the string solver.

Debug information in string solver

---

regression/strings-smoke-tests/java_length/test.desc

Solves this issue: https://github.com/diffblue/test-gen/issues/738

Escape square brackets in java_length test descriptor

---

src/util/fresh_symbol.cpp
src/util/ssa_expr.cpp

Document what symbol name suffices beginning with $, !, @ and # mean,
at the points in the code where they are created.

Document $, !, @ and # in symbol names

---

regression/strings-smoke-tests/java_contains/test_contains.java
regression/strings-smoke-tests/java_contains/test_string_printable.desc

The test causes CBMC to keep using memory until it crashes. Additionally, by using `--verbosity 10`, it can be seen that currently the `--string-printable` option does NOT enforce that nondet strings only contain printable (ASCII) characters.
This relates to diffblue/test-gen/issues/563, and this test will be used to investigate diffblue/test-gen/issues/745.

Added KNOWNBUG regression test for `--string-printable`

---

src/java_bytecode/java_bytecode_typecheck_expr.cpp
src/java_bytecode/java_entry_point.cpp
src/java_bytecode/java_utils.cpp
src/java_bytecode/java_utils.h

This is ported over from test-gen, but really belongs here since the identifiers are assigned by the java-bytecode-convert-method module. This puts the function in a shared location ready for test-gen to use it.

Add a utility for spotting string literal identifiers

---

regression/failed-tests-printer.pl
regression/test.pl

Changes test.pl to name output *.out files after *.desc instead
of *.class files. Also updates failed-test-printer.pl to work with
those new *.out files and multiple *.desc files.

Adapt perl script to handle multiple .desc files (test-gen-support edition)

---

src/goto-instrument/cover.cpp
src/goto-instrument/cover.h

Extended the existing-coverage option to support bytecode_index, 
given the current JSON format to specify goals for C and Java programs.
This PR https://github.com/diffblue/test-gen/pull/760 contains the regression 
tests for C and Java programs to check the existing-coverage option

extended the existing-coverage option to support bytecode_index

---

src/solvers/refinement/string_constraint_generator_transformation.cpp

The length of the result and input of the functions where used in the
wrong place.

Fix axioms introduced for StringBuilder.setLength

---

regression/test.pl

Fixes the following issue: https://github.com/diffblue/test-gen/issues/862#event-1187579258
Fixes a bug where test.pl would ignore directories that contain
valid tests (*.desc and *.java combo) and only test those directories
that contained a file with exact name "test.desc".

test.pl - go through all child directories

---

regression/ansi-c/Struct_Initialization1/test.desc
regression/ansi-c/Struct_Initialization2/main.c
regression/ansi-c/Struct_Initialization2/test.desc
src/ansi-c/c_typecheck_base.h
src/ansi-c/c_typecheck_initializer.cpp
src/ansi-c/designator.h

In the past, this failed an internal assertion; nowadays a proper error is
reported to the user. clang -Werror says:
```
Struct_Initialization1/main.c:9:38: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
struct _classinfo nullclass1 = { 42, 0, 0 };
^~~~
{   }
1 error generated.
```

Array initialization with a non-array is expected to fail

---

src/solvers/refinement/string_refinement.cpp

In `string_refinement::set_to()` there was a missing call to `supert::set_to()`;
Refactored some code in `string_refinement::set_to()`.
This fixes issue diffblue/test-gen#847.

Fix crash with exceptions and --string-refine

---

src/solvers/miniBDD/miniBDD.cpp

This adds a non-recursive variant of APPLY, for systems that have limited stacks.
The commit retains the recursive variant, which is much easier to read.

miniBDD: added a non-recursive variant of APPLY

---

regression/strings-smoke-tests/java_format/test_warning.desc
regression/strings-smoke-tests/java_format2/test_warning.desc
regression/strings-smoke-tests/java_format3/test_warning.desc

Elicits the type inconsistency warnings generated by the `String.format` tests.

Add skipped regression tests for #1202

---

src/solvers/miniBDD/miniBDD.cpp
src/solvers/miniBDD/miniBDD.h
src/util/invariant.h
unit/Makefile
unit/miniBDD_new.cpp

This fixes a segfault in ebmc -- this may even be worth a position in a whitepaper on test generation!

fix for operator< on reverse_keyt in miniBDD, fixing segfault in ebmc

---

src/path-symex/path_symex.cpp
src/path-symex/path_symex_state.cpp
src/path-symex/path_symex_state.h
src/path-symex/path_symex_state_read.cpp
src/path-symex/var_map.h
src/symex/path_search.cpp
src/symex/path_search.h
src/symex/symex_parse_options.cpp
src/symex/symex_parse_options.h

Major performance improvement (taking one of my examples from 13s to 0.3s) when dealing with larger static arrays via  c6a92a8; the other patches are mostly cleanup and some improvements to output. Finally a new option to perform time-limited search (aa3a00d).

Symex improvements

---

regression/cbmc/fgets1/main.c
regression/cbmc/fgets1/test.desc
src/ansi-c/library/getopt.c
src/ansi-c/library/stdio.c

Even though this includes minor bug fixes I'd rather consider these enhancements - not adding a "bugfix" label.

C library modelling: fgets, getopt, vasprintf

---

src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_parser.cpp
src/java_bytecode/java_local_variable_table.cpp
src/solvers/flattening/boolbv_member.cpp
src/solvers/flattening/pointer_logic.cpp
src/util/std_expr.cpp
src/util/std_expr.h
unit/analyses/ai/ai_simplify_lhs.cpp

The solver back end cannot necessarily handle unbounded integers. Do not use
them unless explicitly requested/supported.
Fixes: #1015
This is an alternative approach over #1016.

Avoid using integer_typet where unsuitable

---

src/symex/path_search.cpp
src/symex/path_search.h

Follow-up to 260e03d4184d8: all comparisons are guarded by checks that the
signed integer is >= 0, thus casts to unsigned are safe.

Avoid spurious signed/unsigned comparison warnings

---

regression/cbmc/dynamic_size1/main.c
regression/cbmc/dynamic_size1/test.desc
src/pointer-analysis/value_set_dereference.cpp

Previously the code would rely on type sizes being constant when building a
subtraction; this is unnecessary as the expression is sent to the solver for
evaluation anyway.
~The code should be adjusted once #1063 is merged, thus marking do-not-merge for now.~

Support out-of-bounds checks on arrays of dynamic size

---

regression/cbmc/union9/main.c
regression/cbmc/union9/test.desc
src/solvers/flattening/boolbv_extractbits.cpp
src/solvers/flattening/flatten_byte_operators.cpp

Extractbits can safely be applied to any type as it just turns the bit sequence
into a bitvector; thus use extractbits directly instead of performing type casts
(which are not as generic) first.
Fix a missing struct operands push where the operand had been constructed but
was never used.
Fixes: #1209

Enable extractbits over arbitrary types, fix byte extract omission

---

CODING_STANDARD.md
src/util/ieee_float.cpp
src/util/pipe_stream.cpp

Updates a couple of places where C headers were being used instead of C++ ones.

Stop using C headers

---

src/util/expr.cpp
src/util/expr.h
src/util/expr_iterator.h
unit/Makefile
unit/util/expr_iterator.cpp

Attempts to solve this: https://github.com/diffblue/cbmc/issues/1160
Implements forward iterator, that traverses expression tree by
exploring each expression's operands() vector using depth-first
traversal.
Adds exprt member functions for obtaining said iterator.

Implement depth-first search iterators of exprt class

---

src/cpp/cpp_constructor.cpp
src/util/graph.h
src/util/invariant.h

Trivial fixes. Let's see if this is enough to make the Doxygen/Travis script happy.

Fix Doxygen warnings

---

src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_format.cpp
src/solvers/refinement/string_refinement.cpp
src/util/unicode.cpp
src/util/unicode.h

Fixes the following issue: https://github.com/diffblue/test-gen/issues/194

Escape ["] character in generated tests

---

regression/test.pl

Fixes the following issue: https://github.com/diffblue/test-gen/issues/862#event-1187579258
Fixes a bug where test.pl would ignore directories that contain
valid tests (*.desc and *.java combo) and only test those directories
that contained a file with exact name "test.desc".

test.pl - go through all child directories [master edition]

---

scripts/travis_doxygen.sh
scripts/travis_lint.sh

Travis' shallow clones always use the master branch instead of the PR's target branch which causes the target branch to be unavailable for comparisons. This PR has a workaround.
The  fix is not necessary for master, but should be applied to master as well to facilitate merging.

Fix linter and doxygen checks on travis

---

src/java_bytecode/java_string_library_preprocess.cpp

This allows CBMC to know about which classes these extends and
implement.
The goal is to fix an issue with inheritance https://github.com/diffblue/test-gen/issues/804

Adding base types of the String(Builder|Buffer) classes

---

src/goto-programs/cfg.h
src/goto-programs/goto_program.cpp
src/goto-programs/goto_program_template.h
src/util/graph.h

This started as an effort to understand how _exactly_ `instructiont` is used in the context of https://github.com/diffblue/test-gen/issues/690, but the issue got deprioritized and I'm now trying to merge this only.
This PR only adds documentation, no functional change.
The following classes have been documented:
- grapht
- cfg_baset
- goto_program_templatet
- goto_program_templatet::instructiont

Documentation for goto_program_templatet and cfg_baset

---

src/solvers/Makefile
src/solvers/refinement/string_constraint.h
src/solvers/refinement/string_constraint_instantiation.cpp
src/solvers/refinement/string_constraint_instantiation.h
src/solvers/refinement/string_refinement.cpp
src/solvers/refinement/string_refinement.h
unit/Makefile
unit/solvers/refinement/string_constraint_instantiation/instantiate_not_contains.cpp

The function `string_refinementt::instantiate_not_contains` has been mostly replaced by a stub. The reasoning is that this function, along with others such as `instantiate` and the functions it uses, are loosely coupled with `string_refinementt`. This is a first step for removing these functions. The main purpose is to write unit tests for the currently broken `instantiate_not_contains`. 
Added unit tests for `instantiate_not_contains`.

Unit tests for `solvers/refinement/string_constraint_instantiation.cpp:instantiate_not_contains`

---

src/util/unicode.cpp

Test-gen PR: https://github.com/diffblue/test-gen/pull/914
Somewhat related to this issue: https://github.com/diffblue/test-gen/issues/194

Escape backslash in generated tests [Hotfix]

---

regression/cbmc/Float-Rounding3/main.c
regression/cbmc/Float-Rounding3/test.desc
scripts/cpplint.py
src/ansi-c/clang_builtin_headers.h
src/ansi-c/library/float.c

clang has a builtin to implement FLT_ROUNDS.
gcc appears to hard-wire that to 1.

support clang's __builtin_flt_rounds

---

src/util/simplify_expr_int.cpp

This simplifies x & 1111, where '1111' has the width of x, to x.

simplifier: erase 'all ones' out of bitand

---

src/solvers/refinement/string_refinement.cpp
src/solvers/refinement/string_refinement.h
unit/Makefile
unit/solvers/refinement/string_refinement/substitute_array_list.cpp

When transforming array-list to (ARRAYOF/WITH) expression, we ignore
out of bounds indexes, there value are not meaningfull and may force
cbmc to allocate big arrays when trying to output concrete values.
This also adds unit test for this function.

Making substitute_array_list ignore out of bounds indexes

---

src/util/message.h

Already approved on master (but not yet merged): https://github.com/diffblue/cbmc/pull/1142
@reuk @peterschrammel Could you approve this as well?
Changes message::mstream object to mutable so that message::debug()
and its friends can be run by constant methods.
Warning: in the future, when implementing multiple threads,
implementation of get_mstream will have to be changed so that each
thread has its own, local standard output. As it stands each
get_mstream() call changes stream type for the whole program.

Make message::get_mstream const

---

regression/invariants/Makefile
regression/invariants/driver.cpp
regression/invariants/invariant-failure13/test.desc
src/util/Makefile
src/util/invariant.cpp
src/util/invariant_utils.cpp
src/util/invariant_utils.h

Add a standard template invariant that includes an irept member and pretty-prints it on failure

Add standard invariant subclass with irep member

---

src/goto-programs/goto_program.h

The same as #1246.
I tried building with CXXFLAGS=-D_GLIBCXX_DEBUG and got a compile error, because the compiler couldn't convert between const and non-const "safe"-iterators in one place. Adding an explicit comparator for non-const iterators solves the problem.

[TGS] Add non-const target comparator

---

src/java_bytecode/ci_lazy_methods.cpp
src/java_bytecode/ci_lazy_methods.h
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_bytecode_language.h
src/java_bytecode/java_object_factory.cpp
src/java_bytecode/select_pointer_type.cpp
src/java_bytecode/select_pointer_type.h

When considering the types passed around, we perform a dry run on the pointer substitution to see if there are other types we should be loading for that specific pointer type. This involved some refactoring to ensure the same `pointer_type_selector` is used both at the actual substitution and in loading. 
The tests in test-gen are updated to use `--lazy-methods` flag to ensure this fix works.

Load substituted pointers lazily 

---

src/java_bytecode/jar_file.cpp
src/java_bytecode/jar_file.h
src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_class.h
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_class_loader.cpp
src/java_bytecode/java_class_loader.h
src/util/namespace.h

Fixes https://github.com/diffblue/test-gen/issues/771
The fix for the issue is only the last commit. All other commits essentially improve documentation or debugging output. I advise to review one commit at a time.
During the conversion of bytecode to `codet`, when we discover a call to a
method for which we don't have neither a symbol nor a body, we create a new
symbol in the symbol table. Previously we didn't associate a visibility to its
type. We now associated a public visibility. Not associating a visibility will
cause an INVARIANT failure in `is_method_inherited()`.

Public opaque methods + documentation

---

src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_insert.cpp
src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_constraint_generator_valueof.cpp

This should not affect the behaviour of CBMC as it only removes functions that were never called, and some style changes to make the linter happy.

Removing unreachable and unused code in string constraint generation

---

.travis.yml

1. Linter + Doxygen + non-debug Ubuntu/gcc-5 test - linting, documentation
and build on standard OS with standard compilator with non-debug flags.
This will fail fast in case of trivial error and do not waste Travis
resources.
2. Test different OS/CXX/Flags - rest of combinations we support. This
stage will start only if first one will pass.

Split jobs to two stages in Travis

---

.travis.yml
scripts/run_diff.sh
scripts/travis_doxygen.sh
scripts/travis_lint.sh

None of this is my work - these are commits already merged into test-gen-support.

[tgs->master] continuous integration fixes and workarounds

---

src/solvers/refinement/string_constraint_generator_comparison.cpp
src/solvers/refinement/string_constraint_generator_concat.cpp
src/solvers/refinement/string_constraint_generator_constants.cpp
src/solvers/refinement/string_constraint_generator_float.cpp
src/solvers/refinement/string_constraint_generator_indexof.cpp
src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_constraint_generator_testing.cpp
src/solvers/refinement/string_constraint_generator_transformation.cpp
src/solvers/refinement/string_constraint_generator_valueof.cpp
src/solvers/refinement/string_refinement.cpp
src/util/refined_string_type.cpp
src/util/refined_string_type.h
src/util/string_expr.h

The names used previously (like `axioms_for_is_longer_than`) could be
ambiguous and sometimes misleading.

Rename string expr functions having misleading names 

---

src/java_bytecode/java_utils.cpp

Regardless of the CBMC architecture, which dictates the pointer width used, Java pointers always occupy one slot, as if they were a 32-bit type.

Force Java pointers to always occupy one stack slot

---

src/goto-programs/Makefile
src/goto-programs/link_goto_model.cpp
src/goto-programs/link_goto_model.h
src/goto-programs/read_goto_binary.cpp

This moves functionality to link a goto model into a separate file, for later use by get_goto_model

factor out goto model linking into separate file

---

src/goto-programs/goto_program.h

I tried building with `CXXFLAGS=-D_GLIBCXX_DEBUG` and got a compile error, because the compiler couldn't convert between const and non-const "safe"-iterators in one place. Adding an explicit comparator for non-const iterators solves the problem.

[develop->master] Add non-const target comparator

---

src/cbmc/fault_localization.cpp
src/cbmc/fault_localization.h

This is a simple patch to add XML output for the fault localization result, aiming to resolve issue #674.
As an example, the fault localization result is formatted in the following form. Does it make sense?
`````
<fault-localization>
<diagnosis property="main.assertion.1">
<method>linear fault localization</method>
<result>most likely fault location:  file ../fault-localization/minmax.c line 7 function main</result>
</diagnosis>
</fault-localization>
`````

Fix the output of the fault localization result in XML

---

src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_object_factory.cpp
src/java_bytecode/java_types.cpp
src/java_bytecode/java_types.h

Essentially serves to programatically document what is expected of a Java array type when represented in GOTO.
Also added "real" documentation in the same place. 
test-gen PR: diffblue/test-gen#784

Added check for a type being a valid formed Java array

---

src/java_bytecode/java_bytecode_convert_method.cpp

As title. Required to support TG-110.

Suppress loading notModelled method from CProver library

---

src/goto-programs/builtin_functions.cpp
src/goto-programs/remove_exceptions.cpp
src/java_bytecode/java_bytecode_convert_class.cpp
src/java_bytecode/java_bytecode_convert_method.cpp
src/java_bytecode/java_bytecode_instrument.cpp
src/java_bytecode/java_string_library_preprocess.cpp

Pointer types will require a width, and thus, either java_reference_type() or pointer_type() must be used.

Pointer width fixup

---

src/memory-models/Makefile
src/util/ui_message.cpp

Without this commit, the JSON output will miss source locations of messages. Compare the following plaintext output from cbmc:
```
file My.java line 8 function java::My.doIt:()V: no identifier for function parameter
```
with the JSON output for the same input file and parameters
```
{
"messageText": "no identifier for function parameter",
"messageType": "ERROR"
}
```
---
With this commit, the JSON output will be something like
```
{
"messageText": "no identifier for function parameter",
"messageType": "ERROR"
"sourceLocation": {
"bytecodeIndex": "2"
"file": "My.java",
"function": "java::My.doIt:()V",
"line": "8"
}
}
```
This should make debugging of errors easier.
Jira issue for this is [TG-438] (Diffblue login required)

Add source location to JSON output

---

src/java_bytecode/Makefile
src/java_bytecode/jar_file.cpp
src/java_bytecode/jar_file.h
src/java_bytecode/java_bytecode_language.cpp
src/java_bytecode/java_class_loader.cpp
src/java_bytecode/java_class_loader.h
src/java_bytecode/mz_zip_archive.cpp
src/java_bytecode/mz_zip_archive.h

Architecturally:
- Separates a discrete thin wrapper around `mz_zip_archive` C library
- Preserves the original interface of `jar_filet` excluding object construction
- Drops dependence on `messaget`, `irept` and `dstringt` and removes C header slightly lowering build time
- Inlines  `jar_poolt` and debug messages into `java_class_loadert`
- Protects the class against accidental inheritance
Fixes sleeping bugs:
- Potential memory leak by using bare `new`
- Copying `jar_poolt` or `jar_filet` (which contained state of the C library) would leave the program in an invalid state
- Proper white space trimming of the values of the manifest file
Documents `jar_filet` and the `mz_zip_archivet` wrapper.

Refactor, fix and document jar_filet class

---

src/util/file_util.cpp
src/util/json_expr.cpp
src/util/xml_expr.cpp

This outputs the working directory of source locations both in XML output and json output.
The naming conventions of the respective communities are used, i.e., it's working-directory in XML and workingDirectory in json.

output the working directory for source locations in XML and json

---

src/analyses/goto_rw.h
src/analyses/local_bitvector_analysis.cpp
src/analyses/local_bitvector_analysis.h
src/goto-instrument/wmm/cycle_collection.cpp
src/goto-instrument/wmm/data_dp.cpp
src/goto-instrument/wmm/data_dp.h
src/goto-instrument/wmm/event_graph.cpp
src/goto-instrument/wmm/event_graph.h
src/goto-programs/cfg.h
src/goto-programs/format_strings.h
src/musketeer/ilp.h
src/musketeer/propagate_const_function_pointers.cpp
src/pointer-analysis/value_set.cpp
src/pointer-analysis/value_set.h
src/pointer-analysis/value_set_fi.cpp
src/pointer-analysis/value_set_fi.h
src/util/expanding_vector.h
src/util/numbering.h
src/util/union_find.h

The std containers aren't designed to be inherited-from. This patch aims to replace inheritance from std containers with composition. It also removes util/error.h because it seems that this file isn't included anywhere. Let me know if that should be done in a different PR.

Stop inheriting from std containers

---

src/analyses/goto_rw.h

The last run of the CI for the merged result of #919 was quite old. Although there were no merge conflicts, some extra code was added in the meantime which broke the build. This patch adjusts some of the function signatures in `goto_rw.h`, allowing the new code to work as intended.
Suggest @thk123 and @LAJW to review.

Update function signatures in goto_rw, fixing build

---

src/java_bytecode/java_bytecode_convert_method.cpp

This patch fixes https://diffblue.atlassian.net/browse/TG-390.
Below is a java class, with the disassembly for the `doIt` method on that class.
```java
public class test {
public enum Foo { BAR; }
public Foo doIt() { return Foo.BAR; }
}
```
```
public com.diffblue.regression.test$Foo doIt();
Code:
0: getstatic     #2                  // Field com/diffblue/regression/test$Foo.BAR:Lcom/diffblue/regression/test$Foo;
3: areturn
```
Note that the argument to `getstatic` is a reference to a static object, rather than being a plain object.
This patch ensures that the class of the static object is loaded when lazy-methods are enabled.

Lazy-load static symbols which are accessed through pointers

---

src/cbmc/cbmc_solvers.cpp
src/solvers/refinement/bv_refinement.h
src/solvers/refinement/bv_refinement_loop.cpp
src/solvers/refinement/refine_arithmetic.cpp
src/solvers/refinement/string_constraint.h
src/solvers/refinement/string_constraint_generator.h
src/solvers/refinement/string_constraint_generator_code_points.cpp
src/solvers/refinement/string_constraint_generator_comparison.cpp
src/solvers/refinement/string_constraint_generator_concat.cpp
src/solvers/refinement/string_constraint_generator_constants.cpp
src/solvers/refinement/string_constraint_generator_float.cpp
src/solvers/refinement/string_constraint_generator_format.cpp
src/solvers/refinement/string_constraint_generator_indexof.cpp
src/solvers/refinement/string_constraint_generator_main.cpp
src/solvers/refinement/string_constraint_generator_testing.cpp
src/solvers/refinement/string_constraint_generator_transformation.cpp
src/solvers/refinement/string_constraint_generator_valueof.cpp
src/solvers/refinement/string_refinement.cpp
src/solvers/refinement/string_refinement.h
src/util/constexpr.def
unit/solvers/refinement/string_constraint_generator_valueof/calculate_max_string_length.cpp
unit/solvers/refinement/string_constraint_instantiation/instantiate_not_contains.cpp

Applies following changes to string_refinement directory:
- Gets rid of setter methods.
- Constructs objects using "essence pattern" (struct of attributes). Named `*_infot` (after Vulkan API, which uses the same pattern whenever number of function arguments exceeds 3).
- Groups class member declarations together (rather than being scattered between member function declarations).
- Marks non-publicly accessed methods as private and non-inherited classes as final.
- Marks overridden functions as `override`, removes `virtual`.
- Converts global (static) to local state.
- Removes dead code.

Refactor string refinement constructors

---

src/util/message.h

The output when this invariant was violated confused me. This version may help other people.

Clarified INVARIANT message in get_message_handler

---

src/clobber/Makefile
src/goto-diff/Makefile
src/goto-diff/goto_diff_languages.cpp
src/goto-instrument/Makefile
src/symex/Makefile

These are both obsolete, as the corresponding features are no longer optional.

HAVE_BV_REFINEMENT and HAVE_JAVA_BYTECODE are no longer needed

---

.travis.yml
src/ansi-c/Makefile
src/ansi-c/library/fcntl.c
src/ansi-c/library/getopt.c
src/ansi-c/library/inet.c
src/ansi-c/library/math.c
src/ansi-c/library/netdb.c
src/ansi-c/library/new.c
src/ansi-c/library/process.c
src/ansi-c/library/pthread_lib.c
src/ansi-c/library/setjmp.c
src/ansi-c/library/signal.c
src/ansi-c/library/stdio.c
src/ansi-c/library/stdlib.c
src/ansi-c/library/string.c
src/ansi-c/library/time.c
src/ansi-c/library/unistd.c

To avoid future syntax errors creeping in, a check is added for Travis.

C library: cleanup and syntax error fixes

---

CHANGELOG
regression/goto-instrument/harness1/main.c
regression/goto-instrument/harness1/test.desc
src/clobber/clobber_parse_options.cpp
src/goto-instrument/dump_c.cpp
src/goto-instrument/dump_c.h
src/goto-instrument/dump_c_class.h
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-instrument/model_argc_argv.cpp

This collection of patches cleans up argc/argv modelling and enables output via dump-c, which should be of use together with #767 as well.

Test harness output

---

src/cbmc/bmc_cover.cpp
src/goto-programs/json_goto_trace.cpp
src/symex/symex_cover.cpp
src/util/json_expr.h
src/util/simplify_expr_pointer.cpp
unit/Makefile
unit/util/simplify_expr.cpp

Addresses the comments raised in #1271.

JSON code cleanup

---

src/ansi-c/c_misc.cpp

This avoids the use of lower-level snprintf.

MetaChar: use std::stringstream for incremental escaped-string construction

---

src/goto-programs/interpreter.cpp
src/goto-programs/interpreter_class.h
src/goto-programs/interpreter_evaluate.cpp

I believe that this change does alter the semantics as some comparisons looked really weird (and wrong). Please do read with particular care.

Replace 3-valued char by enum

---

src/analyses/goto_rw.cpp
src/util/pointer_offset_size.cpp
src/util/pointer_offset_size.h

member_offset_bits: express member offset in bits instead of bytes

---

appveyor.yml
regression/Makefile
regression/goto-gcc/Makefile
regression/goto-gcc/ignore_cprover_macros/main.c
regression/goto-gcc/ignore_cprover_macros/test.desc
src/goto-cc/compile.cpp
src/goto-cc/compile.h
src/goto-cc/gcc_mode.cpp
src/goto-cc/gcc_mode.h

Input programs containing __CPROVER_assume, __CPROVER_assert etc. can
now be compiled with goto-gcc as well as goto-cc. Previously, the
system compiler would complain about missing function bodies for all of
these CPROVER macros.

goto-gcc removes CPROVER macros for native gcc

---

regression/ansi-c/linker_script_start+end/main.c
regression/ansi-c/linker_script_start+end/script.ld
regression/ansi-c/linker_script_start+end/test.desc
regression/ansi-c/linker_script_start+size/main.c
regression/ansi-c/linker_script_start+size/script.ld
regression/ansi-c/linker_script_start+size/test.desc
regression/ansi-c/linker_script_symbol-only/main.c
regression/ansi-c/linker_script_symbol-only/script.ld
regression/ansi-c/linker_script_symbol-only/test.desc
scripts/ls_parse.py
src/goto-cc/Makefile
src/goto-cc/gcc_mode.cpp
src/goto-cc/gcc_mode.h
src/goto-cc/linker_script_merge.cpp
src/goto-cc/linker_script_merge.h
src/goto-programs/goto_program_template.h
src/solvers/flattening/boolbv.cpp
src/util/magic.h

goto-gcc now runs the ls_parse.py script whenever the target codebase is being compiled with a custom linker script (specified with the -T option). goto-gcc then synthesizes the linker script definitions that ls_parse reported, and adds them to the goto-program as if those definitions were defined in the target C program rather than the linker script.  This solves a problem where the values of some C variables are inaccessible from CBMC because those variables are defined in the linker script rather than the C codebase. It also solves the problem of CBMC not knowing what memory regions are accessible to the C program, again because the memory regions are declared to be valid in the linker script.  This commit also introduces three tests for this functionality.  This commit also fixes a …

Synthesise definitions of linker script symbols

---

regression/goto-gcc/verbosity1/main.c
regression/goto-gcc/verbosity1/test.desc
regression/goto-gcc/verbosity2/main.c
regression/goto-gcc/verbosity2/test.desc
src/goto-cc/gcc_mode.cpp

Verbosity needs to be set before doing any output.
There are unfortunately scripts that do not tolerate the added ASM comments.

fix verbosity in goto-gcc

---

src/goto-programs/goto_inline.cpp
src/goto-programs/goto_inline_class.cpp
src/goto-programs/goto_inline_class.h

This does two things:
1) Use ranged for
2) get rid of a feature that hasn't been in use for >=5 years

Cleanup goto inline

---

regression/invariants/driver.cpp
src/ansi-c/ansi_c_convert_type.cpp
src/ansi-c/c_typecheck_type.cpp
src/cpp/cpp_typecheck_constructor.cpp
src/cpp/cpp_typecheck_conversions.cpp
src/cpp/cpp_typecheck_type.cpp
src/cpp/parse.cpp
src/goto-symex/symex_builtin_functions.cpp
src/goto-symex/symex_dead.cpp
src/goto-symex/symex_decl.cpp
src/java_bytecode/java_bytecode_instrument.cpp
src/java_bytecode/java_string_library_preprocess.cpp
src/java_bytecode/java_types.cpp
src/path-symex/path_symex.cpp
src/pointer-analysis/value_set.cpp
src/util/c_types.cpp
src/util/simplify_expr_pointer.cpp
src/util/std_expr.h
src/util/std_types.h
unit/analyses/does_remove_const/does_expr_lose_const.cpp
unit/analyses/does_remove_const/does_type_preserve_const_correctness.cpp
unit/analyses/does_remove_const/is_type_at_least_as_const_as.cpp

Pointers need to have a bit-width, which is currently pulled into the decision procedures by looking into the config.

Pointers get a width

---

src/analyses/uncaught_exceptions_analysis.cpp
src/analyses/uncaught_exceptions_analysis.h
src/goto-instrument/accelerate/path.h
src/goto-instrument/accelerate/trace_automaton.cpp
src/goto-instrument/accelerate/trace_automaton.h
src/goto-instrument/cover.cpp
src/goto-programs/goto_model.h

some output member functions can be const

Make output methods const

---

regression/goto-gcc/run_diagnostic/main.i
regression/goto-gcc/run_diagnostic/test.desc
src/util/run.cpp

This helped debugging why goto-gcc failed in a semi-broken set up.

Avoid zombie and print diagnostic output if run/execve fails

---

.travis.yml
README.md

Coverity scan will run as separate job in second stage. Ii will terminate
itself as soon as possible if build is not triggered by cron. Therefore
it requires to have cron job setup (Branch:"develop" Intrerval:"Daily" Options:"Do not run if there has been a build in the last 24h") in settings of diffblue/cbmc and
environment variable `COVERITY_SCAN_TOKEN` in the same project settings.
Example of **cron** job - https://travis-ci.org/zemanlx/cbmc/jobs/269950577
Example of **non-cron** job - https://travis-ci.org/zemanlx/cbmc/jobs/269949324

TG-442 Add Coverity scan

---

src/util/expr_cast.h
src/util/std_expr.h
unit/CMakeLists.txt
unit/Makefile
unit/util/expr_cast/expr_cast.cpp
unit/util/expr_cast/expr_undefined_casts.cpp

`expr_dynamic_cast` is proposed as a replacement for the family of `to_*_expr` functions such as `to_symbol_expr`. Its use can be adopted over time and this PR simply introduces the mechanism, implementations for each exprt derived type in std_expr.h and unit tests.
The primary advantage of `expr_dynamic_cast` is that it reduces from three to one the number of things you need to remember to ensure consistency, all you need now is the name of the type to which you are casting.
Previously code has looked like this:
```
void f(exprt *expr)
{
if(expr.id() == ID_symbol)
{
symbol_exprt *symbol=to_symbol_expr(expr);
use_symbol(symbol);
}
}
```
Now code could look like this:
```
void f(exprt *expr)
{
symbol_exprt *symbol=expr_dynamic_cast<symbol_exprt *>(expr);
if(symbol!=nullptr)
{ …
```

Implementation of expr_dynamic_cast

---

src/goto-symex/symex_clean_expr.cpp
src/solvers/flattening/flatten_byte_operators.cpp
src/util/simplify_expr.cpp
src/util/simplify_expr_boolean.cpp

Includes related fixed from the SV-COMP PR #363.

Simplifier and symex rewriting fixes/extensions

---

src/util/dstring.h
src/util/irep_ids.cpp
src/util/string_container.cpp
src/util/string_container.h

Re-targets #1213 to test-gen-support. This patch improves the correctness of the program and will have minimal effects on performance, therefore I suggest we merge it into TGS, and upstream can conduct a detailed performance appraisal if they feel it is necessary there.

Make string_container static init more resilient

---

src/ansi-c/c_nondet_symbol_factory.cpp
src/util/std_code.h

Here is the refactoring that I wasn't able to commit in time before #767 was merged. The first commit is a cherry-pick of #823 to avoid merge conflicts, so it would be good if that PR could be merged first.

Clean up code for pointer function parameters

---

regression/goto-instrument/inline_16/main.c
regression/goto-instrument/inline_16/test.desc
regression/goto-instrument/inline_17/main.c
regression/goto-instrument/inline_17/test.desc
regression/goto-instrument/remove-calls-no-body1/main.c
regression/goto-instrument/remove-calls-no-body1/test.desc
regression/goto-instrument/remove-calls-no-body2/main.c
regression/goto-instrument/remove-calls-no-body2/test.desc
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-programs/Makefile
src/goto-programs/goto_inline.cpp
src/goto-programs/goto_inline_class.cpp
src/goto-programs/goto_inline_class.h
src/goto-programs/remove_calls_no_body.cpp
src/goto-programs/remove_calls_no_body.h

When using ``--inline`` or ``--function-inline`` in goto-instrument, calls to functions without a body are now kept (partial inlining already keeps them).
Additionally there's now a separate analysis pass ``--remove-calls-nobody`` which removes calls to functions without a body and replaces them by a nondet assignment to the return variable and evaluations of the call arguments.

Do not remove calls to functions without a body during inlining

---

regression/cbmc-cpp/CMakeLists.txt
regression/cbmc-cpp/Makefile
regression/goto-cc-cbmc/chain.sh
regression/goto-cc-cbmc/cpp/main.cpp
regression/goto-cc-cbmc/cpp/test.desc
regression/systemc/CMakeLists.txt
regression/systemc/Makefile
src/cpp/cpp_declarator_converter.cpp
src/cpp/cpp_instantiate_template.cpp
src/cpp/cpp_language.cpp
src/cpp/cpp_typecheck_compound_type.cpp
src/cpp/cpp_typecheck_enum_type.cpp
src/cpp/cpp_typecheck_resolve.cpp
src/linking/remove_internal_symbols.cpp
src/util/config.cpp
src/util/symbol.cpp

This is a series of fixes mainly compiled by @peterschrammel plus some additional work of mine.
This includes the following commits to be reviewed:

C++ front end fixes [blocks: #2554]

---

src/cprover/cprover_parse_options.cpp
src/goto-instrument/contracts/memory_predicates.cpp
src/goto-instrument/stack_depth.cpp
src/goto-instrument/synthesizer/expr_enumerator.cpp
src/goto-programs/goto_trace.cpp
src/util/pointer_offset_size.cpp
src/util/simplify_expr.cpp
src/util/simplify_expr_struct.cpp

The C standard does not guarantee that char is exactly 8 bits, and there are DSPs (such Texas Instruments C55x) that do not have 8-bit-bytes. Use the configuration value instead.

Do not hardcode char/bytes having 8 bits
