diffblue/cbmc

src/ansi-c/ansi_c_convert_type.cpp
src/ansi-c/ansi_c_declaration.cpp
src/ansi-c/ansi_c_declaration.h
src/ansi-c/c_storage_spec.cpp
src/ansi-c/c_storage_spec.h
src/ansi-c/c_typecheck_base.cpp
src/ansi-c/parser.y
src/ansi-c/scanner.l
src/goto-programs/read_bin_goto_object.cpp
src/goto-programs/write_goto_binary.cpp
src/langapi/language_ui.cpp
src/util/irep_ids.txt
src/util/symbol.cpp
src/util/symbol.h

The first patch just addresses parsing and enables basic infrastructure. Proper type checking in linking patches will be added to this pull request once #26 and #38 are merged.

Full support for __attribute__((weak))  (weak ELF symbols)

---

src/ansi-c/c_typecheck_base.cpp
src/ansi-c/c_typecheck_base.h
src/ansi-c/c_typecheck_code.cpp
src/ansi-c/parser.y
src/ansi-c/scanner.l
src/goto-instrument/Makefile
src/goto-instrument/code_contracts.cpp
src/goto-instrument/code_contracts.h
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/goto_instrument_parse_options.h
src/goto-instrument/k_induction.cpp
src/goto-instrument/loop_utils.cpp
src/goto-instrument/loop_utils.h
src/goto-programs/goto_convert.cpp
src/goto-programs/goto_convert_class.h
src/util/irep_ids.txt

This patch series introduces preliminary support for annotating loop invariants and function pre-/post-conditions.
This is a duplicate of #18 after restoring all links to the SVN.

Code contracts

---

src/Makefile
src/cbmc/Makefile
src/cbmc/cbmc_languages.cpp
src/goto-analyzer/Makefile
src/goto-analyzer/goto_analyzer_parse_options.cpp
src/goto-cc/Makefile
src/goto-cc/compile.cpp
src/goto-cc/goto_cc_languages.cpp
src/jsil/Makefile
src/jsil/expr2jsil.cpp
src/jsil/expr2jsil.h
src/jsil/jsil_convert.cpp
src/jsil/jsil_convert.h
src/jsil/jsil_entry_point.cpp
src/jsil/jsil_entry_point.h
src/jsil/jsil_internal_additions.cpp
src/jsil/jsil_internal_additions.h
src/jsil/jsil_language.cpp
src/jsil/jsil_language.h
src/jsil/jsil_parse_tree.cpp
src/jsil/jsil_parse_tree.h
src/jsil/jsil_parser.cpp
src/jsil/jsil_parser.h
src/jsil/jsil_typecheck.cpp
src/jsil/jsil_typecheck.h
src/jsil/parser.y
src/jsil/scanner.l

Support for Imperial's [Javascript Intermediate Language](https://github.com/resource-reasoning/JavaScriptVerification). This isn't quite complete yet (type checking to be implemented), but can produce goto programs with minor hacks. More patches to follow.

JSIL (Javscript Intermediate Language) front-end

---

src/goto-programs/goto_inline.cpp
src/goto-symex/symex_function_call.cpp

Various (ab)uses of GCC-C may lead to invocations of functions with fewer-than-necessary arguments despite the type checker being happy. This patch models the semantics of such calls.

Handle missing arguments more gracefully

---

src/ansi-c/parser.y
src/ansi-c/scanner.l

C11 _Noreturn is already supported

Parse the __noreturn__ attribute

---

src/analyses/interval_analysis.cpp
src/analyses/interval_domain.cpp
src/analyses/interval_domain.h
src/analyses/invariant_propagation.h
src/analyses/invariant_set_domain.cpp
src/analyses/invariant_set_domain.h
src/analyses/static_analysis.cpp
src/analyses/static_analysis.h
src/analyses/uninitialized_domain.cpp
src/analyses/uninitialized_domain.h
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/uninitialized.cpp
src/pointer-analysis/value_set_analysis.h
src/pointer-analysis/value_set_domain.h

This patch partly addresses #14. (And replaces #17)

Migrate all uses of static_analysist to ait (except for value_set*)

---

src/util/config.cpp
src/util/config.h

Should fix failing debian-ports builds on these architectures.

Configuration support for HPPA and SH4 architectures

---

src/ansi-c/type2name.cpp
src/linking/linking.cpp

Several bugfixes and minor improvements related to linking of array-typed symbols. There is more to come, but that work will overlap with weak symbols, which will appear in the next pull request.

Linking arrays and compound types

---

src/cbmc/cbmc_dimacs.cpp

Output all variables in dimacs mapping

---

src/goto-programs/Makefile

Fixes the currently failing build.

Compile recently added show_goto_functions.cpp

---

src/goto-analyzer/unreachable_instructions.cpp
src/goto-cc/compile.cpp
src/util/file_util.cpp
src/util/source_location.cpp
src/util/source_location.h

Improvements to full-path output, mainly for dead-code diagnostics

---

src/goto-cc/compile.cpp
src/goto-cc/gcc_cmdline.cpp
src/goto-cc/gcc_mode.cpp

Making goto-gcc act more similar to gcc, and user experience improvements

Minor goto cc extensions

---

src/goto-symex/partial_order_concurrency.cpp

This is a duplicate of #11 after restoring all links to the SVN.

Print statistics about shared memory accesses

---

regression/ansi-c/KnR3/test.desc
src/ansi-c/parser.y

Parse KnR functions returning function pointers

---

src/cbmc/bmc_cover.cpp
src/goto-programs/json_goto_trace.cpp
src/util/json_expr.cpp

The goals list contains information which goals are there and have been covered.
The tests list contains information on the tests generated and which goals are covered by them.
--trace shows the whole trace for each test.

Split test output into goals and tests

---

src/cbmc/bmc_cover.cpp
src/goto-programs/show_goto_functions.cpp

bmc_cover clean-up and miscellaneous json output

---

src/util/json_expr.cpp

Bugfix contributed by Yoshikazu Imai of nu soft.

json struct bugfix

---

src/pointer-analysis/value_set_fi.cpp

Fix as suggested by Peter.

---

regression/cbmc-cover/mcdc10/main.c
regression/cbmc-cover/mcdc10/test.desc
regression/cbmc-cover/mcdc11/main.c
regression/cbmc-cover/mcdc11/test.desc
regression/cbmc-cover/mcdc12/main.c
regression/cbmc-cover/mcdc12/test.desc
regression/cbmc-cover/mcdc13/main.c
regression/cbmc-cover/mcdc13/test.desc
regression/cbmc-cover/mcdc14/main.c
regression/cbmc-cover/mcdc14/test.desc
regression/cbmc-cover/mcdc8/main.c
regression/cbmc-cover/mcdc8/test.desc
regression/cbmc-cover/mcdc9/main.c
regression/cbmc-cover/mcdc9/test.desc

Signed-off-by: Lucas Cordeiro <lucasccordeiro@gmail.com>

add test cases to check MC/DC coverage instrumentation

---

regression/ansi-c/enum8/main.c
regression/ansi-c/enum8/test.desc
src/ansi-c/c_typecheck_type.cpp

Allow floating point expressions in enum initialization

---

regression/cbmc/Quantifiers-assertion/main.c
regression/cbmc/Quantifiers-assertion/test.desc
regression/cbmc/Quantifiers-assignment/main.c
regression/cbmc/Quantifiers-assignment/test.desc
regression/cbmc/Quantifiers-copy/main.c
regression/cbmc/Quantifiers-copy/test.desc
regression/cbmc/Quantifiers-if/main.c
regression/cbmc/Quantifiers-if/test.desc
regression/cbmc/Quantifiers-initialisation/main.c
regression/cbmc/Quantifiers-initialisation/test.desc
regression/cbmc/Quantifiers-initialisation2/main.c
regression/cbmc/Quantifiers-initialisation2/test.desc
regression/cbmc/Quantifiers-invalid-var-range/main.c
regression/cbmc/Quantifiers-invalid-var-range/test.desc
regression/cbmc/Quantifiers-not-exists/main.c
regression/cbmc/Quantifiers-not-exists/test.desc
regression/cbmc/Quantifiers-not/main.c
regression/cbmc/Quantifiers-not/test.desc
regression/cbmc/Quantifiers-two-dimension-array/main.c
regression/cbmc/Quantifiers-two-dimension-array/test.desc
regression/cbmc/Quantifiers-type/main.c
regression/cbmc/Quantifiers-type/test.desc
src/solvers/flattening/boolbv_quantifier.cpp
src/util/simplify_expr_boolean.cpp

- upper/lower bounds are required for the quantifier variable
- implemented the codes in solvers/flatting/

Added support for quantifiers (forall and exists).

---

src/java_bytecode/java_bytecode_convert_method.cpp

Previously it was possible to generate code such as `(void*)someobject->somefield = some_void_typed_local`. This fixes Java method conversion to always generate the more intuitively correct `someobject->somefield = (A*)some_void_typed_local` (i.e. always cast on the RHS), making it clearer what types are involved.
Part of the local variable table improvement series. Companion of https://github.com/diffblue/cbmc-testgen/pull/33

Don't cast field assignments on the LHS

---

.travis.yml

We should also detect maintenance problems in those.

Make Travis build non-default binaries

---

regression/cbmc/address_space_size_limit1/test.c
regression/cbmc/address_space_size_limit1/test.desc
src/solvers/flattening/bv_pointers.cpp

See https://github.com/diffblue/cbmc/issues/243

Fix address space size check

---

.travis.yml

This should increase the build performance.

Use container-based Travis builds

---

src/util/expr.cpp

Reverts diffblue/cbmc#438 -- please do not put language-specifics into util/*

Revert "direct support for ID_c_bool in exprt"

---

.travis.yml

to support UB checking when running the regression tests

add compilation / link flags for libubsan

---

regression/goto-instrument/slice02/test.desc

This PR fixes the test description of slice02 related to #515

fixed test description of slice02

---

src/goto-symex/symex_goto.cpp

Commit no. 8 from https://github.com/diffblue/cbmc/pull/363

Skip unreachable instructions

---

src/util/infix.h

The companion for `prefix.h` and `suffix.h`

SSS: Add string-infix utility

---

src/util/json_irep.cpp
src/util/json_irep.h

We've already got the serializer in master, and the security scanner needs the reverse translation.

SSS: Add json->irep deserialization routine

---

.travis.yml
src/config.inc
src/util/file_util.cpp
src/util/file_util.h

General purpose filesystem utils. These seem like they belong upstream after some cleaning.

SSS: Filesystem utilities

---

src/util/json_irep.cpp
src/util/json_irep.h

We can already serialize; this adds the corresponding deserialization routine.

Add json->irep deserialization routine

---

src/util/Makefile
src/util/parameter_indices.cpp
src/util/parameter_indices.h

A simple utility for the common task of mapping parameter indices onto their indices. Seems like it'd be generally useful.

SSS: Parameter indexing

---

src/util/std_types.h

This tries to find a this-parameter and returns false (success) if one was found.

SSS: Add get_this utility function

---

src/pointer-analysis/value_set.cpp
src/util/irep_ids.txt
src/util/std_expr.h

This adds the recency attribute and a simple pretty-printer.
Logic actually using the facility is up to an extension module.

Add dynamic-object-expr recency

---

src/util/infix.h

The companion for `prefix.h` and `suffix.h`

Add string-infix utility

---

src/util/sharing_map.h
src/util/sharing_node.h
unit/Makefile
unit/sharing_map.cpp
unit/sharing_node.cpp

This is not used by anything in master yet so should be safe to merge.

Map with sharing

---

src/goto-programs/remove_virtual_functions.cpp

These were introduced because remove-virtual-functions' class hierarchy
walk assumed it was tree-structured, but Java interfaces show up in the
graph like multiple inheritence and falsify that assumption. This simply
truncates the walk when class IDs have been seen before.

Avoid duplicate callee class-ids in virtual dispatch tables. Fixes #684

---

src/util/sparse_vector.h

Add includes to sparse_vector.h

Fix a build issue with test-gen (sparse_vector.h)

---

src/util/irep_ids.def

Add empty string to list of irep ids

---

src/java_bytecode/java_object_factory.cpp

Functionally equivalent, but uses RAII. Also more concise. Makes code
match master, which will make merging easier.

Refactor java object factory

---

src/java_bytecode/expr2java.cpp
src/util/expr.cpp

Fix boolean to string conversion in expr2java

---

src/cegis/cegis-util/type_helper.cpp

Fixes the same formatting issues as #866, but on master.

Fix formatting in cegis-util/type_helper.cpp

---

src/goto-programs/interpreter_evaluate.cpp

This should fix~ diffblue/test-gen#250.

Handle typecast when evaluating addresses in the interpreter

---

regression/cbmc-java/NullPointer1/test.desc
regression/cbmc-java/NullPointer4/test.desc
src/analyses/goto_check.cpp

This fixes~ diffblue/test-gen#243

Set the bytecode index for the instrumentation in goto_check.cpp

---

src/common

Added -O2 to non-Windows compile flags unless -O... is already set

---

regression/cbmc/memory_allocation1/main.c
regression/cbmc/memory_allocation1/test.desc
regression/cbmc/mm_io1/main.c
regression/cbmc/mm_io1/test.desc
src/analyses/goto_check.cpp
src/ansi-c/ansi_c_internal_additions.cpp
src/ansi-c/library/cprover.h
src/cbmc/cbmc_parse_options.cpp
src/goto-programs/Makefile
src/goto-programs/mm_io.cpp
src/goto-programs/mm_io.h
src/pointer-analysis/value_set_dereference.cpp

This is a combination of the diffblue/memory-mapped-IO branch and an additional patch of mine.

Memory-mapped IO support

---

src/java_bytecode/java_bytecode_convert_class.h

Trivial cleanup from master merge

Remove stray include accidentally merged from master

---

src/solvers/sat/satcheck_minisat2.cpp
src/util/graph.h

Follow-up to fix build failure introduced in #1032/9d991b4

Add empty() to grapht as it implements size()

---

src/cbmc/cbmc_parse_options.cpp
src/symex/symex_parse_options.cpp

Depends on https://github.com/diffblue/cbmc/pull/1055
See commit https://github.com/diffblue/cbmc/commit/cd4bac19e5aadbb3c405cb5256d095872bfe0f78 for full detail.

Remove skips before cover annotation

---

.gitignore
src/doxyfile

This PR updates `src/doxyfile` for better support on modern version of `doxygen`:
- Configuration updated from version 1.5 to 1.8
- Added lateral panel
- Clickable inheritance/collaboration diagrams

Updated doxyfile to a modern version

---

src/analyses/call_graph.cpp
src/analyses/call_graph.h
unit/Makefile
unit/analyses/call_graph.cpp

This adds a simple inversion function to get a callee -> caller map.

Add call-graph invert function

---

scripts/bash-autocomplete/Readme.md
scripts/bash-autocomplete/cbmc.sh.template

This required the replacement of calls to `_filedir` in the script.

Add zsh support to auto-complete

---

src/java_bytecode/java_bytecode_instrument.cpp

This ensures that subexpressions are instrumented before their parents, and prevents creation of excessive needless trees of skips and empty blocks as an added bonus, tidying up the output of `--show-symbol-table`.

Restructure java-instrument

---

src/java_bytecode/expr2java.cpp

removed an accidental change, added code to process special cases: NaN and
infinity made required simplications, made corrections in treatment of special
cases
supersedes https://github.com/diffblue/cbmc/pull/1061

generation of  hexadecimal floating point numbers in tests

---

src/goto-programs/remove_exceptions.cpp

Trivial fixes for problems mentioned in https://travis-ci.org/diffblue/cbmc/jobs/262987474

Fix remove-exceptions doxygen

---

scripts/doxy_merge_driver.sh

Adds a merge driver to facilitate doxygen conversions.

Add merge driver

---

src/cbmc/bmc.cpp
src/goto-programs/goto_trace.cpp
src/goto-programs/goto_trace.h
src/goto-programs/graphml_witness.cpp
src/goto-programs/interpreter.cpp
src/goto-programs/json_goto_trace.cpp
src/goto-programs/xml_goto_trace.cpp
src/goto-symex/build_goto_trace.cpp
src/path-symex/build_goto_trace.cpp

See diffblue/test-gen#983 for an explanation.

Make pc private in goto_trace_stept

---

src/cbmc/bmc.cpp
src/goto-programs/goto_trace.cpp
src/goto-programs/goto_trace.h
src/goto-programs/graphml_witness.cpp
src/goto-programs/interpreter.cpp
src/goto-programs/json_goto_trace.cpp
src/goto-programs/xml_goto_trace.cpp
src/goto-symex/build_goto_trace.cpp
src/path-symex/build_goto_trace.cpp

This reverts commit "Make pc private in goto_trace_step".

Revert "Make pc private in goto_trace_step"

---

scripts/cpplint.py

[develop->master] Don't lint text between #if 0...#endif

---

src/goto-instrument/cover.cpp
src/goto-instrument/cover.h
src/goto-instrument/full_slicer.cpp
src/goto-instrument/full_slicer.h
src/goto-instrument/nondet_static.cpp
src/goto-instrument/nondet_static.h
src/goto-programs/convert_nondet.cpp
src/goto-programs/convert_nondet.h
src/goto-programs/remove_skip.cpp
src/goto-programs/remove_skip.h
src/goto-programs/remove_unused_functions.cpp
src/goto-programs/remove_unused_functions.h
src/goto-programs/replace_java_nondet.cpp
src/goto-programs/replace_java_nondet.h
src/goto-programs/string_abstraction.cpp
src/goto-programs/string_abstraction.h
src/goto-programs/string_instrumentation.cpp
src/goto-programs/string_instrumentation.h

This PR adds variants of existing service functions for goto programs using the goto_modelt representation.

variants of service functions for goto_modelt

---

src/cpp/cpp_constructor.cpp
src/goto-symex/symex_builtin_functions.cpp
src/util/graph.h
src/util/invariant.h

None of this is my work - these are commits already merged into test-gen-support.

[develop->master] Documentation fixes

---

src/goto-programs/interpreter.cpp
src/util/std_expr.cpp
src/util/std_expr.h

Remove constant_exprt::integer_constant

---

src/goto-programs/show_goto_functions_json.cpp
src/goto-programs/show_goto_functions_xml.cpp

Fix until https://github.com/diffblue/cbmc/issues/1311 has been done.
Companion: https://github.com/diffblue/test-gen/pull/1024

Flag java internal functions as internal in JSON/XML output

---

.travis.yml
src/ansi-c/Makefile
src/ansi-c/library/fcntl.c
src/ansi-c/library/getopt.c
src/ansi-c/library/inet.c
src/ansi-c/library/math.c
src/ansi-c/library/netdb.c
src/ansi-c/library/new.c
src/ansi-c/library/process.c
src/ansi-c/library/pthread_lib.c
src/ansi-c/library/setjmp.c
src/ansi-c/library/signal.c
src/ansi-c/library/stdio.c
src/ansi-c/library/stdlib.c
src/ansi-c/library/string.c
src/ansi-c/library/time.c
src/ansi-c/library/unistd.c

[develop->master] C library: cleanup and syntax error fixes

---

regression/ansi-c/Union_Padding1/main.c
regression/ansi-c/Union_Padding2/main.c
regression/ansi-c/Union_Padding2/test.desc
regression/cbmc/dynamic_sizeof1/main.c
regression/cbmc/dynamic_sizeof1/test.desc
src/ansi-c/padding.cpp

Union padding fix
